// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pkg/s3x/config.proto

package s3x

import (
	_ "github.com/soyacen/grocer/pkg/protobufx"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/durationpb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       map[string]*Options    `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_pkg_s3x_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_s3x_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_pkg_s3x_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetConfigs() map[string]*Options {
	if x != nil {
		return x.Configs
	}
	return nil
}

type Options struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	AccessKeyId      *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	SecretAccessKey  *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=secret_access_key,json=secretAccessKey,proto3" json:"secret_access_key,omitempty"`
	Bucket           *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=bucket,proto3" json:"bucket,omitempty"`
	BaseEndpoint     *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=base_endpoint,json=baseEndpoint,proto3" json:"base_endpoint,omitempty"`
	UsePathStyle     *wrapperspb.BoolValue   `protobuf:"bytes,5,opt,name=use_path_style,json=usePathStyle,proto3" json:"use_path_style,omitempty"`
	AppId            *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	RetryMaxAttempts *wrapperspb.Int32Value  `protobuf:"bytes,7,opt,name=retry_max_attempts,json=retryMaxAttempts,proto3" json:"retry_max_attempts,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Options) Reset() {
	*x = Options{}
	mi := &file_pkg_s3x_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options) ProtoMessage() {}

func (x *Options) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_s3x_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options.ProtoReflect.Descriptor instead.
func (*Options) Descriptor() ([]byte, []int) {
	return file_pkg_s3x_config_proto_rawDescGZIP(), []int{1}
}

func (x *Options) GetAccessKeyId() *wrapperspb.StringValue {
	if x != nil {
		return x.AccessKeyId
	}
	return nil
}

func (x *Options) GetSecretAccessKey() *wrapperspb.StringValue {
	if x != nil {
		return x.SecretAccessKey
	}
	return nil
}

func (x *Options) GetBucket() *wrapperspb.StringValue {
	if x != nil {
		return x.Bucket
	}
	return nil
}

func (x *Options) GetBaseEndpoint() *wrapperspb.StringValue {
	if x != nil {
		return x.BaseEndpoint
	}
	return nil
}

func (x *Options) GetUsePathStyle() *wrapperspb.BoolValue {
	if x != nil {
		return x.UsePathStyle
	}
	return nil
}

func (x *Options) GetAppId() *wrapperspb.StringValue {
	if x != nil {
		return x.AppId
	}
	return nil
}

func (x *Options) GetRetryMaxAttempts() *wrapperspb.Int32Value {
	if x != nil {
		return x.RetryMaxAttempts
	}
	return nil
}

var File_pkg_s3x_config_proto protoreflect.FileDescriptor

const file_pkg_s3x_config_proto_rawDesc = "" +
	"\n" +
	"\x14pkg/s3x/config.proto\x12\x03s3x\x1a\x1egoogle/protobuf/duration.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x17pkg/protobufx/tls.proto\"\x86\x01\n" +
	"\x06Config\x122\n" +
	"\aconfigs\x18\x01 \x03(\v2\x18.s3x.Config.ConfigsEntryR\aconfigs\x1aH\n" +
	"\fConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\"\n" +
	"\x05value\x18\x02 \x01(\v2\f.s3x.OptionsR\x05value:\x028\x01\"\xd0\x03\n" +
	"\aOptions\x12@\n" +
	"\raccess_key_id\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\vaccessKeyId\x12H\n" +
	"\x11secret_access_key\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x0fsecretAccessKey\x124\n" +
	"\x06bucket\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x06bucket\x12A\n" +
	"\rbase_endpoint\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\fbaseEndpoint\x12@\n" +
	"\x0euse_path_style\x18\x05 \x01(\v2\x1a.google.protobuf.BoolValueR\fusePathStyle\x123\n" +
	"\x06app_id\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\x05appId\x12I\n" +
	"\x12retry_max_attempts\x18\a \x01(\v2\x1b.google.protobuf.Int32ValueR\x10retryMaxAttemptsB'Z%github.com/soyacen/grocer/pkg/s3x;s3xb\x06proto3"

var (
	file_pkg_s3x_config_proto_rawDescOnce sync.Once
	file_pkg_s3x_config_proto_rawDescData []byte
)

func file_pkg_s3x_config_proto_rawDescGZIP() []byte {
	file_pkg_s3x_config_proto_rawDescOnce.Do(func() {
		file_pkg_s3x_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_s3x_config_proto_rawDesc), len(file_pkg_s3x_config_proto_rawDesc)))
	})
	return file_pkg_s3x_config_proto_rawDescData
}

var file_pkg_s3x_config_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_s3x_config_proto_goTypes = []any{
	(*Config)(nil),                 // 0: s3x.Config
	(*Options)(nil),                // 1: s3x.Options
	nil,                            // 2: s3x.Config.ConfigsEntry
	(*wrapperspb.StringValue)(nil), // 3: google.protobuf.StringValue
	(*wrapperspb.BoolValue)(nil),   // 4: google.protobuf.BoolValue
	(*wrapperspb.Int32Value)(nil),  // 5: google.protobuf.Int32Value
}
var file_pkg_s3x_config_proto_depIdxs = []int32{
	2, // 0: s3x.Config.configs:type_name -> s3x.Config.ConfigsEntry
	3, // 1: s3x.Options.access_key_id:type_name -> google.protobuf.StringValue
	3, // 2: s3x.Options.secret_access_key:type_name -> google.protobuf.StringValue
	3, // 3: s3x.Options.bucket:type_name -> google.protobuf.StringValue
	3, // 4: s3x.Options.base_endpoint:type_name -> google.protobuf.StringValue
	4, // 5: s3x.Options.use_path_style:type_name -> google.protobuf.BoolValue
	3, // 6: s3x.Options.app_id:type_name -> google.protobuf.StringValue
	5, // 7: s3x.Options.retry_max_attempts:type_name -> google.protobuf.Int32Value
	1, // 8: s3x.Config.ConfigsEntry.value:type_name -> s3x.Options
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_pkg_s3x_config_proto_init() }
func file_pkg_s3x_config_proto_init() {
	if File_pkg_s3x_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_s3x_config_proto_rawDesc), len(file_pkg_s3x_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_s3x_config_proto_goTypes,
		DependencyIndexes: file_pkg_s3x_config_proto_depIdxs,
		MessageInfos:      file_pkg_s3x_config_proto_msgTypes,
	}.Build()
	File_pkg_s3x_config_proto = out.File
	file_pkg_s3x_config_proto_goTypes = nil
	file_pkg_s3x_config_proto_depIdxs = nil
}
