// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: grocer/temporalx/config.proto

package temporalx

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       map[string]*Options    `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_grocer_temporalx_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_grocer_temporalx_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_grocer_temporalx_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetConfigs() map[string]*Options {
	if x != nil {
		return x.Configs
	}
	return nil
}

type Options struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: To set the host:port for this client to connect to.
	//
	// default: localhost:7233
	//
	// This is a gRPC address and therefore can also support a special-formatted address of "<resolver>:///<value>" that
	// will use a registered resolver. By default all hosts returned from the resolver will be used in a round-robin
	// fashion.
	//
	// The "dns" resolver is registered by and used by default.
	//
	// A custom resolver can be created to provide multiple hosts in other ways. For example, to manually provide
	// multiple IPs to round-robin across, a google.golang.org/grpc/resolver/manual resolver can be created and
	// registered with google.golang.org/grpc/resolver with a custom scheme:
	//
	//	builder := manual.NewBuilderWithScheme("myresolver")
	//	builder.InitialState(resolver.State{Addresses: []resolver.Address{{Addr: "1.2.3.4:1234"}, {Addr: "2.3.4.5:2345"}}})
	//	resolver.Register(builder)
	//	c, err := client.Dial(client.Options{HostPort: "myresolver:///ignoredvalue"})
	//
	// Other more advanced resolvers can also be registered.
	HostPort *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`
	// Optional: To set the namespace name for this client to work with.
	//
	// default: default
	Namespace     *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Options) Reset() {
	*x = Options{}
	mi := &file_grocer_temporalx_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options) ProtoMessage() {}

func (x *Options) ProtoReflect() protoreflect.Message {
	mi := &file_grocer_temporalx_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options.ProtoReflect.Descriptor instead.
func (*Options) Descriptor() ([]byte, []int) {
	return file_grocer_temporalx_config_proto_rawDescGZIP(), []int{1}
}

func (x *Options) GetHostPort() *wrapperspb.StringValue {
	if x != nil {
		return x.HostPort
	}
	return nil
}

func (x *Options) GetNamespace() *wrapperspb.StringValue {
	if x != nil {
		return x.Namespace
	}
	return nil
}

var File_grocer_temporalx_config_proto protoreflect.FileDescriptor

const file_grocer_temporalx_config_proto_rawDesc = "" +
	"\n" +
	"\x1dgrocer/temporalx/config.proto\x12\x10grocer.temporalx\x1a\x1egoogle/protobuf/wrappers.proto\"\xa0\x01\n" +
	"\x06Config\x12?\n" +
	"\aconfigs\x18\x01 \x03(\v2%.grocer.temporalx.Config.ConfigsEntryR\aconfigs\x1aU\n" +
	"\fConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.grocer.temporalx.OptionsR\x05value:\x028\x01\"\x80\x01\n" +
	"\aOptions\x129\n" +
	"\thost_port\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\bhostPort\x12:\n" +
	"\tnamespace\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\tnamespaceB6Z4github.com/soyacen/grocer/grocer/temporalx;temporalxb\x06proto3"

var (
	file_grocer_temporalx_config_proto_rawDescOnce sync.Once
	file_grocer_temporalx_config_proto_rawDescData []byte
)

func file_grocer_temporalx_config_proto_rawDescGZIP() []byte {
	file_grocer_temporalx_config_proto_rawDescOnce.Do(func() {
		file_grocer_temporalx_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grocer_temporalx_config_proto_rawDesc), len(file_grocer_temporalx_config_proto_rawDesc)))
	})
	return file_grocer_temporalx_config_proto_rawDescData
}

var file_grocer_temporalx_config_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grocer_temporalx_config_proto_goTypes = []any{
	(*Config)(nil),                 // 0: grocer.temporalx.Config
	(*Options)(nil),                // 1: grocer.temporalx.Options
	nil,                            // 2: grocer.temporalx.Config.ConfigsEntry
	(*wrapperspb.StringValue)(nil), // 3: google.protobuf.StringValue
}
var file_grocer_temporalx_config_proto_depIdxs = []int32{
	2, // 0: grocer.temporalx.Config.configs:type_name -> grocer.temporalx.Config.ConfigsEntry
	3, // 1: grocer.temporalx.Options.host_port:type_name -> google.protobuf.StringValue
	3, // 2: grocer.temporalx.Options.namespace:type_name -> google.protobuf.StringValue
	1, // 3: grocer.temporalx.Config.ConfigsEntry.value:type_name -> grocer.temporalx.Options
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_grocer_temporalx_config_proto_init() }
func file_grocer_temporalx_config_proto_init() {
	if File_grocer_temporalx_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grocer_temporalx_config_proto_rawDesc), len(file_grocer_temporalx_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grocer_temporalx_config_proto_goTypes,
		DependencyIndexes: file_grocer_temporalx_config_proto_depIdxs,
		MessageInfos:      file_grocer_temporalx_config_proto_msgTypes,
	}.Build()
	File_grocer_temporalx_config_proto = out.File
	file_grocer_temporalx_config_proto_goTypes = nil
	file_grocer_temporalx_config_proto_depIdxs = nil
}
