// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: config.proto

package dbx

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       map[string]*Options    `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetConfigs() map[string]*Options {
	if x != nil {
		return x.Configs
	}
	return nil
}

type Options struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	DriverName      *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=driver_name,json=driverName,proto3" json:"driver_name,omitempty"`
	Dsn             *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=dsn,proto3" json:"dsn,omitempty"`
	PingTimeout     *durationpb.Duration    `protobuf:"bytes,3,opt,name=ping_timeout,json=pingTimeout,proto3" json:"ping_timeout,omitempty"`
	MaxIdleConns    *wrapperspb.Int32Value  `protobuf:"bytes,4,opt,name=max_idle_conns,json=maxIdleConns,proto3" json:"max_idle_conns,omitempty"`
	MaxOpenConns    *wrapperspb.Int32Value  `protobuf:"bytes,5,opt,name=max_open_conns,json=maxOpenConns,proto3" json:"max_open_conns,omitempty"`
	ConnMaxLifetime *durationpb.Duration    `protobuf:"bytes,6,opt,name=conn_max_lifetime,json=connMaxLifetime,proto3" json:"conn_max_lifetime,omitempty"`
	ConnMaxIdleTime *durationpb.Duration    `protobuf:"bytes,7,opt,name=conn_max_idle_time,json=connMaxIdleTime,proto3" json:"conn_max_idle_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Options) Reset() {
	*x = Options{}
	mi := &file_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options) ProtoMessage() {}

func (x *Options) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options.ProtoReflect.Descriptor instead.
func (*Options) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1}
}

func (x *Options) GetDriverName() *wrapperspb.StringValue {
	if x != nil {
		return x.DriverName
	}
	return nil
}

func (x *Options) GetDsn() *wrapperspb.StringValue {
	if x != nil {
		return x.Dsn
	}
	return nil
}

func (x *Options) GetPingTimeout() *durationpb.Duration {
	if x != nil {
		return x.PingTimeout
	}
	return nil
}

func (x *Options) GetMaxIdleConns() *wrapperspb.Int32Value {
	if x != nil {
		return x.MaxIdleConns
	}
	return nil
}

func (x *Options) GetMaxOpenConns() *wrapperspb.Int32Value {
	if x != nil {
		return x.MaxOpenConns
	}
	return nil
}

func (x *Options) GetConnMaxLifetime() *durationpb.Duration {
	if x != nil {
		return x.ConnMaxLifetime
	}
	return nil
}

func (x *Options) GetConnMaxIdleTime() *durationpb.Duration {
	if x != nil {
		return x.ConnMaxIdleTime
	}
	return nil
}

var File_config_proto protoreflect.FileDescriptor

const file_config_proto_rawDesc = "" +
	"\n" +
	"\fconfig.proto\x12\x03dbx\x1a\x1egoogle/protobuf/duration.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x86\x01\n" +
	"\x06Config\x122\n" +
	"\aconfigs\x18\x01 \x03(\v2\x18.dbx.Config.ConfigsEntryR\aconfigs\x1aH\n" +
	"\fConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\"\n" +
	"\x05value\x18\x02 \x01(\v2\f.dbx.OptionsR\x05value:\x028\x01\"\xcb\x03\n" +
	"\aOptions\x12=\n" +
	"\vdriver_name\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"driverName\x12.\n" +
	"\x03dsn\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x03dsn\x12<\n" +
	"\fping_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\vpingTimeout\x12A\n" +
	"\x0emax_idle_conns\x18\x04 \x01(\v2\x1b.google.protobuf.Int32ValueR\fmaxIdleConns\x12A\n" +
	"\x0emax_open_conns\x18\x05 \x01(\v2\x1b.google.protobuf.Int32ValueR\fmaxOpenConns\x12E\n" +
	"\x11conn_max_lifetime\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\x0fconnMaxLifetime\x12F\n" +
	"\x12conn_max_idle_time\x18\a \x01(\v2\x19.google.protobuf.DurationR\x0fconnMaxIdleTimeB\bZ\x06./;dbxb\x06proto3"

var (
	file_config_proto_rawDescOnce sync.Once
	file_config_proto_rawDescData []byte
)

func file_config_proto_rawDescGZIP() []byte {
	file_config_proto_rawDescOnce.Do(func() {
		file_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)))
	})
	return file_config_proto_rawDescData
}

var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_config_proto_goTypes = []any{
	(*Config)(nil),                 // 0: dbx.Config
	(*Options)(nil),                // 1: dbx.Options
	nil,                            // 2: dbx.Config.ConfigsEntry
	(*wrapperspb.StringValue)(nil), // 3: google.protobuf.StringValue
	(*durationpb.Duration)(nil),    // 4: google.protobuf.Duration
	(*wrapperspb.Int32Value)(nil),  // 5: google.protobuf.Int32Value
}
var file_config_proto_depIdxs = []int32{
	2, // 0: dbx.Config.configs:type_name -> dbx.Config.ConfigsEntry
	3, // 1: dbx.Options.driver_name:type_name -> google.protobuf.StringValue
	3, // 2: dbx.Options.dsn:type_name -> google.protobuf.StringValue
	4, // 3: dbx.Options.ping_timeout:type_name -> google.protobuf.Duration
	5, // 4: dbx.Options.max_idle_conns:type_name -> google.protobuf.Int32Value
	5, // 5: dbx.Options.max_open_conns:type_name -> google.protobuf.Int32Value
	4, // 6: dbx.Options.conn_max_lifetime:type_name -> google.protobuf.Duration
	4, // 7: dbx.Options.conn_max_idle_time:type_name -> google.protobuf.Duration
	1, // 8: dbx.Config.ConfigsEntry.value:type_name -> dbx.Options
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}
