// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pkg/mongox/config.proto

package mongox

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       map[string]*Options    `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_pkg_mongox_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mongox_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_pkg_mongox_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetConfigs() map[string]*Options {
	if x != nil {
		return x.Configs
	}
	return nil
}

type Options struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Uri           *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	EnableOtel    *wrapperspb.BoolValue   `protobuf:"bytes,2,opt,name=enable_otel,json=enableOtel,proto3" json:"enable_otel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Options) Reset() {
	*x = Options{}
	mi := &file_pkg_mongox_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options) ProtoMessage() {}

func (x *Options) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_mongox_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options.ProtoReflect.Descriptor instead.
func (*Options) Descriptor() ([]byte, []int) {
	return file_pkg_mongox_config_proto_rawDescGZIP(), []int{1}
}

func (x *Options) GetUri() *wrapperspb.StringValue {
	if x != nil {
		return x.Uri
	}
	return nil
}

func (x *Options) GetEnableOtel() *wrapperspb.BoolValue {
	if x != nil {
		return x.EnableOtel
	}
	return nil
}

var File_pkg_mongox_config_proto protoreflect.FileDescriptor

const file_pkg_mongox_config_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/mongox/config.proto\x12\x06mongox\x1a\x1egoogle/protobuf/wrappers.proto\"\x8c\x01\n" +
	"\x06Config\x125\n" +
	"\aconfigs\x18\x01 \x03(\v2\x1b.mongox.Config.ConfigsEntryR\aconfigs\x1aK\n" +
	"\fConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.mongox.OptionsR\x05value:\x028\x01\"v\n" +
	"\aOptions\x12.\n" +
	"\x03uri\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\x03uri\x12;\n" +
	"\venable_otel\x18\x02 \x01(\v2\x1a.google.protobuf.BoolValueR\n" +
	"enableOtelB-Z+github.com/soyacen/grocer/pkg/mongox;mongoxb\x06proto3"

var (
	file_pkg_mongox_config_proto_rawDescOnce sync.Once
	file_pkg_mongox_config_proto_rawDescData []byte
)

func file_pkg_mongox_config_proto_rawDescGZIP() []byte {
	file_pkg_mongox_config_proto_rawDescOnce.Do(func() {
		file_pkg_mongox_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_mongox_config_proto_rawDesc), len(file_pkg_mongox_config_proto_rawDesc)))
	})
	return file_pkg_mongox_config_proto_rawDescData
}

var file_pkg_mongox_config_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_mongox_config_proto_goTypes = []any{
	(*Config)(nil),                 // 0: mongox.Config
	(*Options)(nil),                // 1: mongox.Options
	nil,                            // 2: mongox.Config.ConfigsEntry
	(*wrapperspb.StringValue)(nil), // 3: google.protobuf.StringValue
	(*wrapperspb.BoolValue)(nil),   // 4: google.protobuf.BoolValue
}
var file_pkg_mongox_config_proto_depIdxs = []int32{
	2, // 0: mongox.Config.configs:type_name -> mongox.Config.ConfigsEntry
	3, // 1: mongox.Options.uri:type_name -> google.protobuf.StringValue
	4, // 2: mongox.Options.enable_otel:type_name -> google.protobuf.BoolValue
	1, // 3: mongox.Config.ConfigsEntry.value:type_name -> mongox.Options
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_mongox_config_proto_init() }
func file_pkg_mongox_config_proto_init() {
	if File_pkg_mongox_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_mongox_config_proto_rawDesc), len(file_pkg_mongox_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_mongox_config_proto_goTypes,
		DependencyIndexes: file_pkg_mongox_config_proto_depIdxs,
		MessageInfos:      file_pkg_mongox_config_proto_msgTypes,
	}.Build()
	File_pkg_mongox_config_proto = out.File
	file_pkg_mongox_config_proto_goTypes = nil
	file_pkg_mongox_config_proto_depIdxs = nil
}
