// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: config/config.proto

package config

import (
	dbx "github.com/soyacen/grocer/grocer/dbx"
	esx "github.com/soyacen/grocer/grocer/esx"
	jeagerx "github.com/soyacen/grocer/grocer/jeagerx"
	kafkax "github.com/soyacen/grocer/grocer/kafkax"
	mongox "github.com/soyacen/grocer/grocer/mongox"
	nacosx "github.com/soyacen/grocer/grocer/nacosx"
	pyroscopex "github.com/soyacen/grocer/grocer/pyroscopex"
	redisx "github.com/soyacen/grocer/grocer/redisx"
	s3x "github.com/soyacen/grocer/grocer/s3x"
	temporalx "github.com/soyacen/grocer/grocer/temporalx"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Db            *dbx.Config            `protobuf:"bytes,1,opt,name=db,proto3" json:"db,omitempty"`
	Es            *esx.Config            `protobuf:"bytes,2,opt,name=es,proto3" json:"es,omitempty"`
	Jeager        *jeagerx.Config        `protobuf:"bytes,3,opt,name=jeager,proto3" json:"jeager,omitempty"`
	Kafka         *kafkax.Config         `protobuf:"bytes,4,opt,name=kafka,proto3" json:"kafka,omitempty"`
	Mongo         *mongox.Config         `protobuf:"bytes,5,opt,name=mongo,proto3" json:"mongo,omitempty"`
	Nacos         *nacosx.Config         `protobuf:"bytes,6,opt,name=nacos,proto3" json:"nacos,omitempty"`
	Pyroscope     *pyroscopex.Config     `protobuf:"bytes,8,opt,name=pyroscope,proto3" json:"pyroscope,omitempty"`
	Redis         *redisx.Config         `protobuf:"bytes,9,opt,name=redis,proto3" json:"redis,omitempty"`
	S3            *s3x.Config            `protobuf:"bytes,10,opt,name=s3,proto3" json:"s3,omitempty"`
	Temporal      *temporalx.Config      `protobuf:"bytes,11,opt,name=temporal,proto3" json:"temporal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_config_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_config_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_config_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetDb() *dbx.Config {
	if x != nil {
		return x.Db
	}
	return nil
}

func (x *Config) GetEs() *esx.Config {
	if x != nil {
		return x.Es
	}
	return nil
}

func (x *Config) GetJeager() *jeagerx.Config {
	if x != nil {
		return x.Jeager
	}
	return nil
}

func (x *Config) GetKafka() *kafkax.Config {
	if x != nil {
		return x.Kafka
	}
	return nil
}

func (x *Config) GetMongo() *mongox.Config {
	if x != nil {
		return x.Mongo
	}
	return nil
}

func (x *Config) GetNacos() *nacosx.Config {
	if x != nil {
		return x.Nacos
	}
	return nil
}

func (x *Config) GetPyroscope() *pyroscopex.Config {
	if x != nil {
		return x.Pyroscope
	}
	return nil
}

func (x *Config) GetRedis() *redisx.Config {
	if x != nil {
		return x.Redis
	}
	return nil
}

func (x *Config) GetS3() *s3x.Config {
	if x != nil {
		return x.S3
	}
	return nil
}

func (x *Config) GetTemporal() *temporalx.Config {
	if x != nil {
		return x.Temporal
	}
	return nil
}

var File_config_config_proto protoreflect.FileDescriptor

const file_config_config_proto_rawDesc = "" +
	"\n" +
	"\x13config/config.proto\x12\rgrocer.config\x1a#third_party/grocer/dbx/config.proto\x1a#third_party/grocer/esx/config.proto\x1a'third_party/grocer/jeagerx/config.proto\x1a&third_party/grocer/kafkax/config.proto\x1a&third_party/grocer/mongox/config.proto\x1a&third_party/grocer/nacosx/config.proto\x1a*third_party/grocer/pyroscopex/config.proto\x1a&third_party/grocer/redisx/config.proto\x1a#third_party/grocer/s3x/config.proto\x1a)third_party/grocer/temporalx/config.proto\"\xc7\x03\n" +
	"\x06Config\x12\"\n" +
	"\x02db\x18\x01 \x01(\v2\x12.grocer.dbx.ConfigR\x02db\x12\"\n" +
	"\x02es\x18\x02 \x01(\v2\x12.grocer.esx.ConfigR\x02es\x12.\n" +
	"\x06jeager\x18\x03 \x01(\v2\x16.grocer.jeagerx.ConfigR\x06jeager\x12+\n" +
	"\x05kafka\x18\x04 \x01(\v2\x15.grocer.kafkax.ConfigR\x05kafka\x12+\n" +
	"\x05mongo\x18\x05 \x01(\v2\x15.grocer.mongox.ConfigR\x05mongo\x12+\n" +
	"\x05nacos\x18\x06 \x01(\v2\x15.grocer.nacosx.ConfigR\x05nacos\x127\n" +
	"\tpyroscope\x18\b \x01(\v2\x19.grocer.pyroscopex.ConfigR\tpyroscope\x12+\n" +
	"\x05redis\x18\t \x01(\v2\x15.grocer.redisx.ConfigR\x05redis\x12\"\n" +
	"\x02s3\x18\n" +
	" \x01(\v2\x12.grocer.s3x.ConfigR\x02s3\x124\n" +
	"\btemporal\x18\v \x01(\v2\x18.grocer.temporalx.ConfigR\btemporalB9Z7github.com/soyacen/grocer/internal/layout/config;configb\x06proto3"

var (
	file_config_config_proto_rawDescOnce sync.Once
	file_config_config_proto_rawDescData []byte
)

func file_config_config_proto_rawDescGZIP() []byte {
	file_config_config_proto_rawDescOnce.Do(func() {
		file_config_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_config_proto_rawDesc), len(file_config_config_proto_rawDesc)))
	})
	return file_config_config_proto_rawDescData
}

var file_config_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_config_config_proto_goTypes = []any{
	(*Config)(nil),            // 0: grocer.config.Config
	(*dbx.Config)(nil),        // 1: grocer.dbx.Config
	(*esx.Config)(nil),        // 2: grocer.esx.Config
	(*jeagerx.Config)(nil),    // 3: grocer.jeagerx.Config
	(*kafkax.Config)(nil),     // 4: grocer.kafkax.Config
	(*mongox.Config)(nil),     // 5: grocer.mongox.Config
	(*nacosx.Config)(nil),     // 6: grocer.nacosx.Config
	(*pyroscopex.Config)(nil), // 7: grocer.pyroscopex.Config
	(*redisx.Config)(nil),     // 8: grocer.redisx.Config
	(*s3x.Config)(nil),        // 9: grocer.s3x.Config
	(*temporalx.Config)(nil),  // 10: grocer.temporalx.Config
}
var file_config_config_proto_depIdxs = []int32{
	1,  // 0: grocer.config.Config.db:type_name -> grocer.dbx.Config
	2,  // 1: grocer.config.Config.es:type_name -> grocer.esx.Config
	3,  // 2: grocer.config.Config.jeager:type_name -> grocer.jeagerx.Config
	4,  // 3: grocer.config.Config.kafka:type_name -> grocer.kafkax.Config
	5,  // 4: grocer.config.Config.mongo:type_name -> grocer.mongox.Config
	6,  // 5: grocer.config.Config.nacos:type_name -> grocer.nacosx.Config
	7,  // 6: grocer.config.Config.pyroscope:type_name -> grocer.pyroscopex.Config
	8,  // 7: grocer.config.Config.redis:type_name -> grocer.redisx.Config
	9,  // 8: grocer.config.Config.s3:type_name -> grocer.s3x.Config
	10, // 9: grocer.config.Config.temporal:type_name -> grocer.temporalx.Config
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_config_config_proto_init() }
func file_config_config_proto_init() {
	if File_config_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_config_proto_rawDesc), len(file_config_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_config_proto_goTypes,
		DependencyIndexes: file_config_config_proto_depIdxs,
		MessageInfos:      file_config_config_proto_msgTypes,
	}.Build()
	File_config_config_proto = out.File
	file_config_config_proto_goTypes = nil
	file_config_config_proto_depIdxs = nil
}
