// Code generated by protoc-gen-gonfig. DO NOT EDIT.

package config

import (
	context "context"
	gonfig "github.com/soyacen/gonfig"
	resource "github.com/soyacen/gonfig/resource"
	dbx "github.com/soyacen/grocer/grocer/dbx"
	esx "github.com/soyacen/grocer/grocer/esx"
	jeagerx "github.com/soyacen/grocer/grocer/jeagerx"
	kafkax "github.com/soyacen/grocer/grocer/kafkax"
	mongox "github.com/soyacen/grocer/grocer/mongox"
	nacosx "github.com/soyacen/grocer/grocer/nacosx"
	pyroscopex "github.com/soyacen/grocer/grocer/pyroscopex"
	redisx "github.com/soyacen/grocer/grocer/redisx"
	s3x "github.com/soyacen/grocer/grocer/s3x"
	proto "google.golang.org/protobuf/proto"
	atomic "sync/atomic"
)

var (
	_Config atomic.Value
)

func init() {
	_Config.Store(&Config{})
}

func LoadConfig(ctx context.Context, resource resource.Resource) error {
	conf, err := gonfig.Load[*Config](ctx, resource)
	if err != nil {
		return err
	}
	_Config.Store(conf)
	return nil
}

func WatchConfig(ctx context.Context, resource resource.Resource, errFunc resource.ErrFunc) (resource.StopFunc, error) {
	stopFunc, err := gonfig.Watch[*Config](ctx, resource, func(conf *Config) { _Config.Store(conf) }, errFunc)
	if err != nil {
		return nil, err
	}
	return stopFunc, nil
}

func GetConfig() *Config {
	return proto.Clone(_Config.Load().(*Config)).(*Config)
}

func GetDb() *dbx.Config {
	return proto.Clone(_Config.Load().(*Config).GetDb()).(*dbx.Config)
}

func GetEs() *esx.Config {
	return proto.Clone(_Config.Load().(*Config).GetEs()).(*esx.Config)
}

func GetJeager() *jeagerx.Config {
	return proto.Clone(_Config.Load().(*Config).GetJeager()).(*jeagerx.Config)
}

func GetKafka() *kafkax.Config {
	return proto.Clone(_Config.Load().(*Config).GetKafka()).(*kafkax.Config)
}

func GetMongo() *mongox.Config {
	return proto.Clone(_Config.Load().(*Config).GetMongo()).(*mongox.Config)
}

func GetNacos() *nacosx.Config {
	return proto.Clone(_Config.Load().(*Config).GetNacos()).(*nacosx.Config)
}

func GetPyroscope() *pyroscopex.Config {
	return proto.Clone(_Config.Load().(*Config).GetPyroscope()).(*pyroscopex.Config)
}

func GetRedis() *redisx.Config {
	return proto.Clone(_Config.Load().(*Config).GetRedis()).(*redisx.Config)
}

func GetS3() *s3x.Config {
	return proto.Clone(_Config.Load().(*Config).GetS3()).(*s3x.Config)
}
