# gRPC 服务的 Kubernetes 部署配置
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocer-grpc
  namespace: default
  labels:
    app: grocer-grpc
spec:
  replicas: 3  # 根据需要调整副本数
  selector:
    matchLabels:
      app: grocer-grpc
  template:
    metadata:
      labels:
        app: grocer-grpc
    spec:
      containers:
      - name: grocer-grpc
        image: soyacen/layout:latest  # 替换为实际的镜像名称
        command: ["./project"]
        args: ["grpc"]  # 启动 gRPC 服务
        ports:
        - containerPort: 8081  # gRPC 默认端口，可根据需要调整
          name: grpc
        env:
        # 添加必要的环境变量
        - name: ENV
          value: "production"
        - name: GRPC_PORT
          value: "8081"
        imagePullPolicy: Always  # 总是拉取最新镜像
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        startupProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 30
          successThreshold: 1
        livenessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
---
# gRPC 服务的 Service 配置
apiVersion: v1
kind: Service
metadata:
  name: grocer-grpc-service
  namespace: default
  labels:
    app: grocer-grpc
spec:
  selector:
    app: grocer-grpc
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: grpc
  type: ClusterIP  # 使用 ClusterIP 类型，仅集群内部访问