# K8s CronJob配置文件，用于定期执行job
apiVersion: batch/v1
kind: CronJob
metadata:
  name: grocer-job
  namespace: default
  labels:
    app: grocer
spec:
  schedule: "*/30 * * * *"  # 每30分钟执行一次
  concurrencyPolicy: Forbid  # 禁止并发执行
  startingDeadlineSeconds: 60  # 如果错过了执行时间60秒以上，则放弃执行
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: grocer-cronjob
            image: soyacen/grocer:latest  # 替换为实际的镜像名称
            command:
            - /bin/sh
            - -c
            - ./project job  # 执行job命令
            env:
            # 添加必要的环境变量
            - name: ENV
              value: "production"
            imagePullPolicy: Always  # 总是拉取最新镜像
            resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
              limits:
                memory: "256Mi"
                cpu: "200m"
          restartPolicy: OnFailure  # 只有在失败时才重启
---
# 如果需要，也可以添加一个普通Job示例
apiVersion: batch/v1
kind: Job
metadata:
  name: grocer-one-time-job
  namespace: default
  labels:
    app: grocer
spec:
  template:
    spec:
      containers:
      - name: grocer-job
        image: soyacen/grocer:latest  # 替换为实际的镜像名称
        command:
        - /bin/sh
        - -c
        - ./project job  # 执行job命令
        env:
        # 添加必要的环境变量
        - name: ENV
          value: "production"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      restartPolicy: OnFailure