// Code generated by protoc-gen-goose. DO NOT EDIT.

package grpc

import (
	bytes "bytes"
	context "context"
	errors "errors"
	goose "github.com/soyacen/goose"
	client "github.com/soyacen/goose/client"
	resolver "github.com/soyacen/goose/client/resolver"
	server "github.com/soyacen/goose/server"
	protojson "google.golang.org/protobuf/encoding/protojson"
	http "net/http"
)

type GreeterService interface {
	SayHello(ctx context.Context, req *HelloRequest) (*HelloReply, error)
}

func AppendGreeterRoute(router *http.ServeMux, service GreeterService, opts ...server.Option) *http.ServeMux {
	options := server.NewOptions(opts...)
	handler := greeterHandler{
		service: service,
		decoder: greeterRequestDecoder{
			unmarshalOptions: options.UnmarshalOptions(),
		},
		encoder: greeterResponseEncoder{
			marshalOptions:   options.MarshalOptions(),
			unmarshalOptions: options.UnmarshalOptions(),
		},
		errorEncoder:            options.ErrorEncoder(),
		shouldFailFast:          options.ShouldFailFast(),
		onValidationErrCallback: options.OnValidationErrCallback(),
		middleware:              server.Chain(options.Middlewares()...),
	}
	router.Handle("POST /grocer.grpc.v1.Greeter/SayHello", http.HandlerFunc(handler.SayHello))
	return router
}

type greeterHandler struct {
	service                 GreeterService
	decoder                 greeterRequestDecoder
	encoder                 greeterResponseEncoder
	errorEncoder            goose.ErrorEncoder
	shouldFailFast          bool
	onValidationErrCallback goose.OnValidationErrCallback
	middleware              server.Middleware
}

func (h greeterHandler) SayHello(response http.ResponseWriter, request *http.Request) {
	invoke := func(response http.ResponseWriter, request *http.Request) {
		ctx := request.Context()
		req, err := h.decoder.SayHello(ctx, request)
		if err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
		if err := goose.ValidateRequest(ctx, req, h.shouldFailFast, h.onValidationErrCallback); err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
		resp, err := h.service.SayHello(ctx, req)
		if err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
		if err := h.encoder.SayHello(ctx, response, resp); err != nil {
			h.errorEncoder(ctx, err, response)
			return
		}
	}
	server.Invoke(h.middleware, response, request, invoke)
}

type greeterRequestDecoder struct {
	unmarshalOptions protojson.UnmarshalOptions
}

func (decoder greeterRequestDecoder) SayHello(ctx context.Context, request *http.Request) (*HelloRequest, error) {
	req := &HelloRequest{}
	ok, err := server.CustomDecodeRequest(ctx, request, req)
	if err != nil {
		return nil, err
	}
	if ok {
		return req, nil
	}
	if err := server.DecodeRequest(ctx, request, req, decoder.unmarshalOptions); err != nil {
		return nil, err
	}
	return req, nil
}

type greeterResponseEncoder struct {
	marshalOptions   protojson.MarshalOptions
	unmarshalOptions protojson.UnmarshalOptions
}

func (encoder greeterResponseEncoder) SayHello(ctx context.Context, w http.ResponseWriter, resp *HelloReply) error {
	return server.EncodeResponse(ctx, w, resp, encoder.marshalOptions)
}

func NewGreeterClient(target string, opts ...client.Option) GreeterService {
	options := client.NewOptions(opts...)
	client := &greeterClient{
		client: options.Client(),
		encoder: greeterRequestEncoder{
			target:         target,
			marshalOptions: options.MarshalOptions(),
			resolver:       options.Resolver(),
		},
		decoder: greeterResponseDecoder{
			unmarshalOptions: options.UnmarshalOptions(),
			errorDecoder:     options.ErrorDecoder(),
			errorFactory:     options.ErrorFactory(),
		},
		shouldFailFast:          options.ShouldFailFast(),
		onValidationErrCallback: options.OnValidationErrCallback(),
		middleware:              client.Chain(options.Middlewares()...),
	}
	return client
}

type greeterClient struct {
	client                  *http.Client
	encoder                 greeterRequestEncoder
	decoder                 greeterResponseDecoder
	shouldFailFast          bool
	onValidationErrCallback goose.OnValidationErrCallback
	middleware              client.Middleware
}

func (c *greeterClient) SayHello(ctx context.Context, req *HelloRequest) (*HelloReply, error) {
	if err := goose.ValidateRequest(ctx, req, c.shouldFailFast, c.onValidationErrCallback); err != nil {
		return nil, err
	}
	request, err := c.encoder.SayHello(ctx, req)
	if err != nil {
		return nil, err
	}
	response, err := client.Invoke(c.middleware, c.client, request)
	if err != nil {
		return nil, err
	}
	resp, err := c.decoder.SayHello(ctx, response)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

type greeterRequestEncoder struct {
	target         string
	marshalOptions protojson.MarshalOptions
	resolver       resolver.Resolver
}

func (encoder *greeterRequestEncoder) SayHello(ctx context.Context, req *HelloRequest) (*http.Request, error) {
	if req == nil {
		return nil, errors.New("request is nil")
	}
	target, err := resolver.Resolve(ctx, encoder.resolver, encoder.target)
	if err != nil {
		return nil, err
	}
	method := "POST"
	header := http.Header{}
	var body bytes.Buffer
	if err := client.EncodeMessage(ctx, req, header, &body, encoder.marshalOptions); err != nil {
		return nil, err
	}
	path := "/grocer.grpc.v1.Greeter/SayHello"
	target.Path = path
	request, err := http.NewRequestWithContext(ctx, method, target.String(), &body)
	if err != nil {
		return nil, err
	}
	goose.CopyHeader(request.Header, header)
	return request, nil
}

type greeterResponseDecoder struct {
	unmarshalOptions protojson.UnmarshalOptions
	errorDecoder     goose.ErrorDecoder
	errorFactory     goose.ErrorFactory
}

func (decoder *greeterResponseDecoder) SayHello(ctx context.Context, response *http.Response) (*HelloReply, error) {
	if respErr, ok := decoder.errorDecoder(ctx, response, decoder.errorFactory); ok {
		return nil, respErr
	}
	resp := &HelloReply{}
	if err := client.DecodeMessage(ctx, response, resp, decoder.unmarshalOptions); err != nil {
		return nil, err
	}
	return resp, nil
}
