// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pkg/esx/config.proto

package esx

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       map[string]*Options    `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_pkg_esx_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_esx_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_pkg_esx_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetConfigs() map[string]*Options {
	if x != nil {
		return x.Configs
	}
	return nil
}

type Options struct {
	state                  protoimpl.MessageState  `protogen:"open.v1"`
	Addresses              []string                `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`                                                               // A list of Elasticsearch nodes to use.
	Username               *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=username,proto3,oneof" json:"username,omitempty"`                                                           // Username for HTTP Basic Authentication.
	Password               *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=password,proto3,oneof" json:"password,omitempty"`                                                           // Password for HTTP Basic Authentication.
	CloudId                *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=cloud_id,json=cloudId,proto3,oneof" json:"cloud_id,omitempty"`                                              // Endpoint for the Elastic Service (https://elastic.co/cloud).
	ApiKey                 *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=api_key,json=apiKey,proto3,oneof" json:"api_key,omitempty"`                                                 // Base64-encoded token for authorization; if set, overrides username/password and service token.
	ServiceToken           *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=service_token,json=serviceToken,proto3,oneof" json:"service_token,omitempty"`                               // Service token for authorization; if set, overrides username/password.
	CertificateFingerprint *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=certificate_fingerprint,json=certificateFingerprint,proto3,oneof" json:"certificate_fingerprint,omitempty"` // SHA256 hex fingerprint given by Elasticsearch on first launch.
	// Header represents http.Header
	Header map[string]string `protobuf:"bytes,8,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Global HTTP request header.
	// PEM-encoded certificate authorities.
	CaCert                   *wrapperspb.BytesValue `protobuf:"bytes,9,opt,name=ca_cert,json=caCert,proto3,oneof" json:"ca_cert,omitempty"`                                                            // When set, an empty certificate pool will be created, and the certificates will be appended to it.
	RetryOnStatus            []int32                `protobuf:"varint,10,rep,packed,name=retry_on_status,json=retryOnStatus,proto3" json:"retry_on_status,omitempty"`                                  // List of status codes for retry. Default: 502, 503, 504.
	DisableRetry             *wrapperspb.BoolValue  `protobuf:"bytes,11,opt,name=disable_retry,json=disableRetry,proto3,oneof" json:"disable_retry,omitempty"`                                         // Default: false.
	MaxRetries               *wrapperspb.Int32Value `protobuf:"bytes,12,opt,name=max_retries,json=maxRetries,proto3,oneof" json:"max_retries,omitempty"`                                               // Default: 3.
	CompressRequestBody      *wrapperspb.BoolValue  `protobuf:"bytes,13,opt,name=compress_request_body,json=compressRequestBody,proto3,oneof" json:"compress_request_body,omitempty"`                  // Default: false.
	CompressRequestBodyLevel *wrapperspb.Int32Value `protobuf:"bytes,14,opt,name=compress_request_body_level,json=compressRequestBodyLevel,proto3,oneof" json:"compress_request_body_level,omitempty"` // Default: gzip.DefaultCompression.
	PoolCompressor           *wrapperspb.BoolValue  `protobuf:"bytes,15,opt,name=pool_compressor,json=poolCompressor,proto3,oneof" json:"pool_compressor,omitempty"`                                   // If true, a sync.Pool based gzip writer is used. Default: false.
	DiscoverNodesOnStart     *wrapperspb.BoolValue  `protobuf:"bytes,16,opt,name=discover_nodes_on_start,json=discoverNodesOnStart,proto3,oneof" json:"discover_nodes_on_start,omitempty"`             // Discover nodes when initializing the client. Default: false.
	DiscoverNodesInterval    *wrapperspb.Int64Value `protobuf:"bytes,17,opt,name=discover_nodes_interval,json=discoverNodesInterval,proto3,oneof" json:"discover_nodes_interval,omitempty"`            // Discover nodes periodically in milliseconds. Default: disabled.
	EnableMetrics            *wrapperspb.BoolValue  `protobuf:"bytes,18,opt,name=enable_metrics,json=enableMetrics,proto3,oneof" json:"enable_metrics,omitempty"`                                      // Enable the metrics collection.
	EnableDebugLogger        *wrapperspb.BoolValue  `protobuf:"bytes,19,opt,name=enable_debug_logger,json=enableDebugLogger,proto3,oneof" json:"enable_debug_logger,omitempty"`                        // Enable the debug logging.
	EnableCompatibilityMode  *wrapperspb.BoolValue  `protobuf:"bytes,20,opt,name=enable_compatibility_mode,json=enableCompatibilityMode,proto3,oneof" json:"enable_compatibility_mode,omitempty"`      // Enable sends compatibility header
	DisableMetaHeader        *wrapperspb.BoolValue  `protobuf:"bytes,21,opt,name=disable_meta_header,json=disableMetaHeader,proto3,oneof" json:"disable_meta_header,omitempty"`                        // Disable the additional "X-Elastic-Client-Meta" HTTP header.
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Options) Reset() {
	*x = Options{}
	mi := &file_pkg_esx_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options) ProtoMessage() {}

func (x *Options) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_esx_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options.ProtoReflect.Descriptor instead.
func (*Options) Descriptor() ([]byte, []int) {
	return file_pkg_esx_config_proto_rawDescGZIP(), []int{1}
}

func (x *Options) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *Options) GetUsername() *wrapperspb.StringValue {
	if x != nil {
		return x.Username
	}
	return nil
}

func (x *Options) GetPassword() *wrapperspb.StringValue {
	if x != nil {
		return x.Password
	}
	return nil
}

func (x *Options) GetCloudId() *wrapperspb.StringValue {
	if x != nil {
		return x.CloudId
	}
	return nil
}

func (x *Options) GetApiKey() *wrapperspb.StringValue {
	if x != nil {
		return x.ApiKey
	}
	return nil
}

func (x *Options) GetServiceToken() *wrapperspb.StringValue {
	if x != nil {
		return x.ServiceToken
	}
	return nil
}

func (x *Options) GetCertificateFingerprint() *wrapperspb.StringValue {
	if x != nil {
		return x.CertificateFingerprint
	}
	return nil
}

func (x *Options) GetHeader() map[string]string {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Options) GetCaCert() *wrapperspb.BytesValue {
	if x != nil {
		return x.CaCert
	}
	return nil
}

func (x *Options) GetRetryOnStatus() []int32 {
	if x != nil {
		return x.RetryOnStatus
	}
	return nil
}

func (x *Options) GetDisableRetry() *wrapperspb.BoolValue {
	if x != nil {
		return x.DisableRetry
	}
	return nil
}

func (x *Options) GetMaxRetries() *wrapperspb.Int32Value {
	if x != nil {
		return x.MaxRetries
	}
	return nil
}

func (x *Options) GetCompressRequestBody() *wrapperspb.BoolValue {
	if x != nil {
		return x.CompressRequestBody
	}
	return nil
}

func (x *Options) GetCompressRequestBodyLevel() *wrapperspb.Int32Value {
	if x != nil {
		return x.CompressRequestBodyLevel
	}
	return nil
}

func (x *Options) GetPoolCompressor() *wrapperspb.BoolValue {
	if x != nil {
		return x.PoolCompressor
	}
	return nil
}

func (x *Options) GetDiscoverNodesOnStart() *wrapperspb.BoolValue {
	if x != nil {
		return x.DiscoverNodesOnStart
	}
	return nil
}

func (x *Options) GetDiscoverNodesInterval() *wrapperspb.Int64Value {
	if x != nil {
		return x.DiscoverNodesInterval
	}
	return nil
}

func (x *Options) GetEnableMetrics() *wrapperspb.BoolValue {
	if x != nil {
		return x.EnableMetrics
	}
	return nil
}

func (x *Options) GetEnableDebugLogger() *wrapperspb.BoolValue {
	if x != nil {
		return x.EnableDebugLogger
	}
	return nil
}

func (x *Options) GetEnableCompatibilityMode() *wrapperspb.BoolValue {
	if x != nil {
		return x.EnableCompatibilityMode
	}
	return nil
}

func (x *Options) GetDisableMetaHeader() *wrapperspb.BoolValue {
	if x != nil {
		return x.DisableMetaHeader
	}
	return nil
}

var File_pkg_esx_config_proto protoreflect.FileDescriptor

const file_pkg_esx_config_proto_rawDesc = "" +
	"\n" +
	"\x14pkg/esx/config.proto\x12\x03esx\x1a\x1egoogle/protobuf/wrappers.proto\"\x86\x01\n" +
	"\x06Config\x122\n" +
	"\aconfigs\x18\x01 \x03(\v2\x18.esx.Config.ConfigsEntryR\aconfigs\x1aH\n" +
	"\fConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\"\n" +
	"\x05value\x18\x02 \x01(\v2\f.esx.OptionsR\x05value:\x028\x01\"\x8b\x0f\n" +
	"\aOptions\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\tR\taddresses\x12=\n" +
	"\busername\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueH\x00R\busername\x88\x01\x01\x12=\n" +
	"\bpassword\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueH\x01R\bpassword\x88\x01\x01\x12<\n" +
	"\bcloud_id\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueH\x02R\acloudId\x88\x01\x01\x12:\n" +
	"\aapi_key\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueH\x03R\x06apiKey\x88\x01\x01\x12F\n" +
	"\rservice_token\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueH\x04R\fserviceToken\x88\x01\x01\x12Z\n" +
	"\x17certificate_fingerprint\x18\a \x01(\v2\x1c.google.protobuf.StringValueH\x05R\x16certificateFingerprint\x88\x01\x01\x120\n" +
	"\x06header\x18\b \x03(\v2\x18.esx.Options.HeaderEntryR\x06header\x129\n" +
	"\aca_cert\x18\t \x01(\v2\x1b.google.protobuf.BytesValueH\x06R\x06caCert\x88\x01\x01\x12&\n" +
	"\x0fretry_on_status\x18\n" +
	" \x03(\x05R\rretryOnStatus\x12D\n" +
	"\rdisable_retry\x18\v \x01(\v2\x1a.google.protobuf.BoolValueH\aR\fdisableRetry\x88\x01\x01\x12A\n" +
	"\vmax_retries\x18\f \x01(\v2\x1b.google.protobuf.Int32ValueH\bR\n" +
	"maxRetries\x88\x01\x01\x12S\n" +
	"\x15compress_request_body\x18\r \x01(\v2\x1a.google.protobuf.BoolValueH\tR\x13compressRequestBody\x88\x01\x01\x12_\n" +
	"\x1bcompress_request_body_level\x18\x0e \x01(\v2\x1b.google.protobuf.Int32ValueH\n" +
	"R\x18compressRequestBodyLevel\x88\x01\x01\x12H\n" +
	"\x0fpool_compressor\x18\x0f \x01(\v2\x1a.google.protobuf.BoolValueH\vR\x0epoolCompressor\x88\x01\x01\x12V\n" +
	"\x17discover_nodes_on_start\x18\x10 \x01(\v2\x1a.google.protobuf.BoolValueH\fR\x14discoverNodesOnStart\x88\x01\x01\x12X\n" +
	"\x17discover_nodes_interval\x18\x11 \x01(\v2\x1b.google.protobuf.Int64ValueH\rR\x15discoverNodesInterval\x88\x01\x01\x12F\n" +
	"\x0eenable_metrics\x18\x12 \x01(\v2\x1a.google.protobuf.BoolValueH\x0eR\renableMetrics\x88\x01\x01\x12O\n" +
	"\x13enable_debug_logger\x18\x13 \x01(\v2\x1a.google.protobuf.BoolValueH\x0fR\x11enableDebugLogger\x88\x01\x01\x12[\n" +
	"\x19enable_compatibility_mode\x18\x14 \x01(\v2\x1a.google.protobuf.BoolValueH\x10R\x17enableCompatibilityMode\x88\x01\x01\x12O\n" +
	"\x13disable_meta_header\x18\x15 \x01(\v2\x1a.google.protobuf.BoolValueH\x11R\x11disableMetaHeader\x88\x01\x01\x1a9\n" +
	"\vHeaderEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\v\n" +
	"\t_usernameB\v\n" +
	"\t_passwordB\v\n" +
	"\t_cloud_idB\n" +
	"\n" +
	"\b_api_keyB\x10\n" +
	"\x0e_service_tokenB\x1a\n" +
	"\x18_certificate_fingerprintB\n" +
	"\n" +
	"\b_ca_certB\x10\n" +
	"\x0e_disable_retryB\x0e\n" +
	"\f_max_retriesB\x18\n" +
	"\x16_compress_request_bodyB\x1e\n" +
	"\x1c_compress_request_body_levelB\x12\n" +
	"\x10_pool_compressorB\x1a\n" +
	"\x18_discover_nodes_on_startB\x1a\n" +
	"\x18_discover_nodes_intervalB\x11\n" +
	"\x0f_enable_metricsB\x16\n" +
	"\x14_enable_debug_loggerB\x1c\n" +
	"\x1a_enable_compatibility_modeB\x16\n" +
	"\x14_disable_meta_headerB'Z%github.com/soyacen/grocer/pkg/esx;esxb\x06proto3"

var (
	file_pkg_esx_config_proto_rawDescOnce sync.Once
	file_pkg_esx_config_proto_rawDescData []byte
)

func file_pkg_esx_config_proto_rawDescGZIP() []byte {
	file_pkg_esx_config_proto_rawDescOnce.Do(func() {
		file_pkg_esx_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_esx_config_proto_rawDesc), len(file_pkg_esx_config_proto_rawDesc)))
	})
	return file_pkg_esx_config_proto_rawDescData
}

var file_pkg_esx_config_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_esx_config_proto_goTypes = []any{
	(*Config)(nil),                 // 0: esx.Config
	(*Options)(nil),                // 1: esx.Options
	nil,                            // 2: esx.Config.ConfigsEntry
	nil,                            // 3: esx.Options.HeaderEntry
	(*wrapperspb.StringValue)(nil), // 4: google.protobuf.StringValue
	(*wrapperspb.BytesValue)(nil),  // 5: google.protobuf.BytesValue
	(*wrapperspb.BoolValue)(nil),   // 6: google.protobuf.BoolValue
	(*wrapperspb.Int32Value)(nil),  // 7: google.protobuf.Int32Value
	(*wrapperspb.Int64Value)(nil),  // 8: google.protobuf.Int64Value
}
var file_pkg_esx_config_proto_depIdxs = []int32{
	2,  // 0: esx.Config.configs:type_name -> esx.Config.ConfigsEntry
	4,  // 1: esx.Options.username:type_name -> google.protobuf.StringValue
	4,  // 2: esx.Options.password:type_name -> google.protobuf.StringValue
	4,  // 3: esx.Options.cloud_id:type_name -> google.protobuf.StringValue
	4,  // 4: esx.Options.api_key:type_name -> google.protobuf.StringValue
	4,  // 5: esx.Options.service_token:type_name -> google.protobuf.StringValue
	4,  // 6: esx.Options.certificate_fingerprint:type_name -> google.protobuf.StringValue
	3,  // 7: esx.Options.header:type_name -> esx.Options.HeaderEntry
	5,  // 8: esx.Options.ca_cert:type_name -> google.protobuf.BytesValue
	6,  // 9: esx.Options.disable_retry:type_name -> google.protobuf.BoolValue
	7,  // 10: esx.Options.max_retries:type_name -> google.protobuf.Int32Value
	6,  // 11: esx.Options.compress_request_body:type_name -> google.protobuf.BoolValue
	7,  // 12: esx.Options.compress_request_body_level:type_name -> google.protobuf.Int32Value
	6,  // 13: esx.Options.pool_compressor:type_name -> google.protobuf.BoolValue
	6,  // 14: esx.Options.discover_nodes_on_start:type_name -> google.protobuf.BoolValue
	8,  // 15: esx.Options.discover_nodes_interval:type_name -> google.protobuf.Int64Value
	6,  // 16: esx.Options.enable_metrics:type_name -> google.protobuf.BoolValue
	6,  // 17: esx.Options.enable_debug_logger:type_name -> google.protobuf.BoolValue
	6,  // 18: esx.Options.enable_compatibility_mode:type_name -> google.protobuf.BoolValue
	6,  // 19: esx.Options.disable_meta_header:type_name -> google.protobuf.BoolValue
	1,  // 20: esx.Config.ConfigsEntry.value:type_name -> esx.Options
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_pkg_esx_config_proto_init() }
func file_pkg_esx_config_proto_init() {
	if File_pkg_esx_config_proto != nil {
		return
	}
	file_pkg_esx_config_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_esx_config_proto_rawDesc), len(file_pkg_esx_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_esx_config_proto_goTypes,
		DependencyIndexes: file_pkg_esx_config_proto_depIdxs,
		MessageInfos:      file_pkg_esx_config_proto_msgTypes,
	}.Build()
	File_pkg_esx_config_proto = out.File
	file_pkg_esx_config_proto_goTypes = nil
	file_pkg_esx_config_proto_depIdxs = nil
}
