// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pkg/protobufx/tls.proto

package protobufx

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TLSOptions contains configuration for TLS connections
type TLSOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path to the TLS certificate file
	CertFile *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=cert_file,json=certFile,proto3" json:"cert_file,omitempty"`
	// Path to the TLS private key file
	KeyFile *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=key_file,json=keyFile,proto3" json:"key_file,omitempty"`
	// Path to the Certificate Authority file
	CaFile *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=ca_file,json=caFile,proto3" json:"ca_file,omitempty"`
	// Server name for SNI (Server Name Indication)
	ServerName    *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLSOptions) Reset() {
	*x = TLSOptions{}
	mi := &file_pkg_protobufx_tls_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSOptions) ProtoMessage() {}

func (x *TLSOptions) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobufx_tls_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSOptions.ProtoReflect.Descriptor instead.
func (*TLSOptions) Descriptor() ([]byte, []int) {
	return file_pkg_protobufx_tls_proto_rawDescGZIP(), []int{0}
}

func (x *TLSOptions) GetCertFile() *wrapperspb.StringValue {
	if x != nil {
		return x.CertFile
	}
	return nil
}

func (x *TLSOptions) GetKeyFile() *wrapperspb.StringValue {
	if x != nil {
		return x.KeyFile
	}
	return nil
}

func (x *TLSOptions) GetCaFile() *wrapperspb.StringValue {
	if x != nil {
		return x.CaFile
	}
	return nil
}

func (x *TLSOptions) GetServerName() *wrapperspb.StringValue {
	if x != nil {
		return x.ServerName
	}
	return nil
}

var File_pkg_protobufx_tls_proto protoreflect.FileDescriptor

const file_pkg_protobufx_tls_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/protobufx/tls.proto\x12\tprotobufx\x1a\x1egoogle/protobuf/wrappers.proto\"\xf6\x01\n" +
	"\n" +
	"TLSOptions\x129\n" +
	"\tcert_file\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\bcertFile\x127\n" +
	"\bkey_file\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\akeyFile\x125\n" +
	"\aca_file\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x06caFile\x12=\n" +
	"\vserver_name\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"serverNameB3Z1github.com/soyacen/grocer/pkg/protobufx;protobufxb\x06proto3"

var (
	file_pkg_protobufx_tls_proto_rawDescOnce sync.Once
	file_pkg_protobufx_tls_proto_rawDescData []byte
)

func file_pkg_protobufx_tls_proto_rawDescGZIP() []byte {
	file_pkg_protobufx_tls_proto_rawDescOnce.Do(func() {
		file_pkg_protobufx_tls_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protobufx_tls_proto_rawDesc), len(file_pkg_protobufx_tls_proto_rawDesc)))
	})
	return file_pkg_protobufx_tls_proto_rawDescData
}

var file_pkg_protobufx_tls_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_protobufx_tls_proto_goTypes = []any{
	(*TLSOptions)(nil),             // 0: protobufx.TLSOptions
	(*wrapperspb.StringValue)(nil), // 1: google.protobuf.StringValue
}
var file_pkg_protobufx_tls_proto_depIdxs = []int32{
	1, // 0: protobufx.TLSOptions.cert_file:type_name -> google.protobuf.StringValue
	1, // 1: protobufx.TLSOptions.key_file:type_name -> google.protobuf.StringValue
	1, // 2: protobufx.TLSOptions.ca_file:type_name -> google.protobuf.StringValue
	1, // 3: protobufx.TLSOptions.server_name:type_name -> google.protobuf.StringValue
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_protobufx_tls_proto_init() }
func file_pkg_protobufx_tls_proto_init() {
	if File_pkg_protobufx_tls_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protobufx_tls_proto_rawDesc), len(file_pkg_protobufx_tls_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_protobufx_tls_proto_goTypes,
		DependencyIndexes: file_pkg_protobufx_tls_proto_depIdxs,
		MessageInfos:      file_pkg_protobufx_tls_proto_msgTypes,
	}.Build()
	File_pkg_protobufx_tls_proto = out.File
	file_pkg_protobufx_tls_proto_goTypes = nil
	file_pkg_protobufx_tls_proto_depIdxs = nil
}
