// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pkg/redisx/config.proto

package redisx

import (
	protobufx "github.com/soyacen/grocer/pkg/protobufx"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       map[string]*Options    `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_pkg_redisx_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_redisx_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_pkg_redisx_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetConfigs() map[string]*Options {
	if x != nil {
		return x.Configs
	}
	return nil
}

type Options struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Either a single address or a seed list of host:port addresses
	// of cluster/sentinel nodes.
	Addrs []string `protobuf:"bytes,1,rep,name=addrs,proto3" json:"addrs,omitempty"`
	// client_name will execute the `CLIENT SETNAME ClientName` command for each conn.
	ClientName *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	// db to be selected after connecting to the server.
	// Only single-node and failover clients.
	Db *wrapperspb.Int32Value `protobuf:"bytes,3,opt,name=db,proto3" json:"db,omitempty"`
	// Common options.
	Protocol              *wrapperspb.Int32Value  `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Username              *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Password              *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	SentinelUsername      *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=sentinel_username,json=sentinelUsername,proto3" json:"sentinel_username,omitempty"`
	SentinelPassword      *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=sentinel_password,json=sentinelPassword,proto3" json:"sentinel_password,omitempty"`
	MaxRetries            *wrapperspb.Int32Value  `protobuf:"bytes,9,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	MinRetryBackoff       *durationpb.Duration    `protobuf:"bytes,10,opt,name=min_retry_backoff,json=minRetryBackoff,proto3" json:"min_retry_backoff,omitempty"`
	MaxRetryBackoff       *durationpb.Duration    `protobuf:"bytes,11,opt,name=max_retry_backoff,json=maxRetryBackoff,proto3" json:"max_retry_backoff,omitempty"`
	DialTimeout           *durationpb.Duration    `protobuf:"bytes,12,opt,name=dial_timeout,json=dialTimeout,proto3" json:"dial_timeout,omitempty"`
	ReadTimeout           *durationpb.Duration    `protobuf:"bytes,13,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	WriteTimeout          *durationpb.Duration    `protobuf:"bytes,14,opt,name=write_timeout,json=writeTimeout,proto3" json:"write_timeout,omitempty"`
	ContextTimeoutEnabled *wrapperspb.BoolValue   `protobuf:"bytes,15,opt,name=context_timeout_enabled,json=contextTimeoutEnabled,proto3" json:"context_timeout_enabled,omitempty"`
	// PoolFIFO uses FIFO mode for each node connection pool GET/PUT (default LIFO).
	PoolFifo        *wrapperspb.BoolValue  `protobuf:"bytes,16,opt,name=pool_fifo,json=poolFifo,proto3" json:"pool_fifo,omitempty"`
	PoolSize        *wrapperspb.Int32Value `protobuf:"bytes,17,opt,name=pool_size,json=poolSize,proto3" json:"pool_size,omitempty"`
	PoolTimeout     *durationpb.Duration   `protobuf:"bytes,18,opt,name=pool_timeout,json=poolTimeout,proto3" json:"pool_timeout,omitempty"`
	MinIdleConns    *wrapperspb.Int32Value `protobuf:"bytes,19,opt,name=min_idle_conns,json=minIdleConns,proto3" json:"min_idle_conns,omitempty"`
	MaxIdleConns    *wrapperspb.Int32Value `protobuf:"bytes,20,opt,name=max_idle_conns,json=maxIdleConns,proto3" json:"max_idle_conns,omitempty"`
	MaxActiveConns  *wrapperspb.Int32Value `protobuf:"bytes,21,opt,name=max_active_conns,json=maxActiveConns,proto3" json:"max_active_conns,omitempty"`
	ConnMaxIdleTime *durationpb.Duration   `protobuf:"bytes,22,opt,name=conn_max_idle_time,json=connMaxIdleTime,proto3" json:"conn_max_idle_time,omitempty"`
	ConnMaxLifetime *durationpb.Duration   `protobuf:"bytes,23,opt,name=conn_max_lifetime,json=connMaxLifetime,proto3" json:"conn_max_lifetime,omitempty"`
	// ReadBufferSize is the size of the bufio.Reader buffer for each connection.
	// Larger buffers can improve performance for commands that return large responses.
	// Smaller buffers can improve memory usage for larger pools.
	ReadBufferSize *wrapperspb.Int32Value `protobuf:"bytes,24,opt,name=read_buffer_size,json=readBufferSize,proto3" json:"read_buffer_size,omitempty"`
	// WriteBufferSize is the size of the bufio.Writer buffer for each connection.
	// Larger buffers can improve performance for large pipelines and commands with many arguments.
	// Smaller buffers can improve memory usage for larger pools.
	WriteBufferSize *wrapperspb.Int32Value `protobuf:"bytes,25,opt,name=write_buffer_size,json=writeBufferSize,proto3" json:"write_buffer_size,omitempty"`
	TlsConfig       *protobufx.TLSOptions  `protobuf:"bytes,26,opt,name=tls_config,json=tlsConfig,proto3" json:"tls_config,omitempty"`
	// Only cluster clients.
	ClusterOptions *Options_ClusterOptions `protobuf:"bytes,27,opt,name=cluster_options,json=clusterOptions,proto3" json:"cluster_options,omitempty"`
	// Only failover clients.
	FailoverOptions *Options_FailOverOptions `protobuf:"bytes,28,opt,name=failover_options,json=failoverOptions,proto3" json:"failover_options,omitempty"`
	DisableIdentity *wrapperspb.BoolValue    `protobuf:"bytes,29,opt,name=disable_identity,json=disableIdentity,proto3" json:"disable_identity,omitempty"`
	IdentitySuffix  *wrapperspb.StringValue  `protobuf:"bytes,30,opt,name=identity_suffix,json=identitySuffix,proto3" json:"identity_suffix,omitempty"`
	// FailingTimeoutSeconds is the timeout in seconds for marking a cluster node as failing.
	FailingTimeoutSeconds *wrapperspb.Int32Value `protobuf:"bytes,31,opt,name=failing_timeout_seconds,json=failingTimeoutSeconds,proto3" json:"failing_timeout_seconds,omitempty"`
	UnstableResp3         *wrapperspb.BoolValue  `protobuf:"bytes,32,opt,name=unstable_resp3,json=unstableResp3,proto3" json:"unstable_resp3,omitempty"`
	// IsClusterMode can be used when only one Addrs is provided (e.g. Elasticache supports setting up cluster mode with configuration endpoint).
	IsClusterMode *wrapperspb.BoolValue `protobuf:"bytes,33,opt,name=is_cluster_mode,json=isClusterMode,proto3" json:"is_cluster_mode,omitempty"`
	// MaintNotificationsConfig provides configuration for maintnotifications upgrades.
	MaintNotificationsConfig *Options_MaintNotificationsConfig `protobuf:"bytes,34,opt,name=maint_notifications_config,json=maintNotificationsConfig,proto3" json:"maint_notifications_config,omitempty"`
	EnableTracing            *wrapperspb.BoolValue             `protobuf:"bytes,35,opt,name=enable_tracing,json=enableTracing,proto3" json:"enable_tracing,omitempty"`
	EnableMetrics            *wrapperspb.BoolValue             `protobuf:"bytes,36,opt,name=enable_metrics,json=enableMetrics,proto3" json:"enable_metrics,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Options) Reset() {
	*x = Options{}
	mi := &file_pkg_redisx_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options) ProtoMessage() {}

func (x *Options) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_redisx_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options.ProtoReflect.Descriptor instead.
func (*Options) Descriptor() ([]byte, []int) {
	return file_pkg_redisx_config_proto_rawDescGZIP(), []int{1}
}

func (x *Options) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *Options) GetClientName() *wrapperspb.StringValue {
	if x != nil {
		return x.ClientName
	}
	return nil
}

func (x *Options) GetDb() *wrapperspb.Int32Value {
	if x != nil {
		return x.Db
	}
	return nil
}

func (x *Options) GetProtocol() *wrapperspb.Int32Value {
	if x != nil {
		return x.Protocol
	}
	return nil
}

func (x *Options) GetUsername() *wrapperspb.StringValue {
	if x != nil {
		return x.Username
	}
	return nil
}

func (x *Options) GetPassword() *wrapperspb.StringValue {
	if x != nil {
		return x.Password
	}
	return nil
}

func (x *Options) GetSentinelUsername() *wrapperspb.StringValue {
	if x != nil {
		return x.SentinelUsername
	}
	return nil
}

func (x *Options) GetSentinelPassword() *wrapperspb.StringValue {
	if x != nil {
		return x.SentinelPassword
	}
	return nil
}

func (x *Options) GetMaxRetries() *wrapperspb.Int32Value {
	if x != nil {
		return x.MaxRetries
	}
	return nil
}

func (x *Options) GetMinRetryBackoff() *durationpb.Duration {
	if x != nil {
		return x.MinRetryBackoff
	}
	return nil
}

func (x *Options) GetMaxRetryBackoff() *durationpb.Duration {
	if x != nil {
		return x.MaxRetryBackoff
	}
	return nil
}

func (x *Options) GetDialTimeout() *durationpb.Duration {
	if x != nil {
		return x.DialTimeout
	}
	return nil
}

func (x *Options) GetReadTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReadTimeout
	}
	return nil
}

func (x *Options) GetWriteTimeout() *durationpb.Duration {
	if x != nil {
		return x.WriteTimeout
	}
	return nil
}

func (x *Options) GetContextTimeoutEnabled() *wrapperspb.BoolValue {
	if x != nil {
		return x.ContextTimeoutEnabled
	}
	return nil
}

func (x *Options) GetPoolFifo() *wrapperspb.BoolValue {
	if x != nil {
		return x.PoolFifo
	}
	return nil
}

func (x *Options) GetPoolSize() *wrapperspb.Int32Value {
	if x != nil {
		return x.PoolSize
	}
	return nil
}

func (x *Options) GetPoolTimeout() *durationpb.Duration {
	if x != nil {
		return x.PoolTimeout
	}
	return nil
}

func (x *Options) GetMinIdleConns() *wrapperspb.Int32Value {
	if x != nil {
		return x.MinIdleConns
	}
	return nil
}

func (x *Options) GetMaxIdleConns() *wrapperspb.Int32Value {
	if x != nil {
		return x.MaxIdleConns
	}
	return nil
}

func (x *Options) GetMaxActiveConns() *wrapperspb.Int32Value {
	if x != nil {
		return x.MaxActiveConns
	}
	return nil
}

func (x *Options) GetConnMaxIdleTime() *durationpb.Duration {
	if x != nil {
		return x.ConnMaxIdleTime
	}
	return nil
}

func (x *Options) GetConnMaxLifetime() *durationpb.Duration {
	if x != nil {
		return x.ConnMaxLifetime
	}
	return nil
}

func (x *Options) GetReadBufferSize() *wrapperspb.Int32Value {
	if x != nil {
		return x.ReadBufferSize
	}
	return nil
}

func (x *Options) GetWriteBufferSize() *wrapperspb.Int32Value {
	if x != nil {
		return x.WriteBufferSize
	}
	return nil
}

func (x *Options) GetTlsConfig() *protobufx.TLSOptions {
	if x != nil {
		return x.TlsConfig
	}
	return nil
}

func (x *Options) GetClusterOptions() *Options_ClusterOptions {
	if x != nil {
		return x.ClusterOptions
	}
	return nil
}

func (x *Options) GetFailoverOptions() *Options_FailOverOptions {
	if x != nil {
		return x.FailoverOptions
	}
	return nil
}

func (x *Options) GetDisableIdentity() *wrapperspb.BoolValue {
	if x != nil {
		return x.DisableIdentity
	}
	return nil
}

func (x *Options) GetIdentitySuffix() *wrapperspb.StringValue {
	if x != nil {
		return x.IdentitySuffix
	}
	return nil
}

func (x *Options) GetFailingTimeoutSeconds() *wrapperspb.Int32Value {
	if x != nil {
		return x.FailingTimeoutSeconds
	}
	return nil
}

func (x *Options) GetUnstableResp3() *wrapperspb.BoolValue {
	if x != nil {
		return x.UnstableResp3
	}
	return nil
}

func (x *Options) GetIsClusterMode() *wrapperspb.BoolValue {
	if x != nil {
		return x.IsClusterMode
	}
	return nil
}

func (x *Options) GetMaintNotificationsConfig() *Options_MaintNotificationsConfig {
	if x != nil {
		return x.MaintNotificationsConfig
	}
	return nil
}

func (x *Options) GetEnableTracing() *wrapperspb.BoolValue {
	if x != nil {
		return x.EnableTracing
	}
	return nil
}

func (x *Options) GetEnableMetrics() *wrapperspb.BoolValue {
	if x != nil {
		return x.EnableMetrics
	}
	return nil
}

type Options_ClusterOptions struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MaxRedirects   *wrapperspb.Int32Value `protobuf:"bytes,1,opt,name=max_redirects,json=maxRedirects,proto3" json:"max_redirects,omitempty"`
	ReadOnly       *wrapperspb.BoolValue  `protobuf:"bytes,2,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	RouteByLatency *wrapperspb.BoolValue  `protobuf:"bytes,3,opt,name=route_by_latency,json=routeByLatency,proto3" json:"route_by_latency,omitempty"`
	RouteRandomly  *wrapperspb.BoolValue  `protobuf:"bytes,4,opt,name=route_randomly,json=routeRandomly,proto3" json:"route_randomly,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Options_ClusterOptions) Reset() {
	*x = Options_ClusterOptions{}
	mi := &file_pkg_redisx_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options_ClusterOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options_ClusterOptions) ProtoMessage() {}

func (x *Options_ClusterOptions) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_redisx_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options_ClusterOptions.ProtoReflect.Descriptor instead.
func (*Options_ClusterOptions) Descriptor() ([]byte, []int) {
	return file_pkg_redisx_config_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Options_ClusterOptions) GetMaxRedirects() *wrapperspb.Int32Value {
	if x != nil {
		return x.MaxRedirects
	}
	return nil
}

func (x *Options_ClusterOptions) GetReadOnly() *wrapperspb.BoolValue {
	if x != nil {
		return x.ReadOnly
	}
	return nil
}

func (x *Options_ClusterOptions) GetRouteByLatency() *wrapperspb.BoolValue {
	if x != nil {
		return x.RouteByLatency
	}
	return nil
}

func (x *Options_ClusterOptions) GetRouteRandomly() *wrapperspb.BoolValue {
	if x != nil {
		return x.RouteRandomly
	}
	return nil
}

type Options_FailOverOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The sentinel master name.
	MasterName    *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=master_name,json=masterName,proto3" json:"master_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Options_FailOverOptions) Reset() {
	*x = Options_FailOverOptions{}
	mi := &file_pkg_redisx_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options_FailOverOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options_FailOverOptions) ProtoMessage() {}

func (x *Options_FailOverOptions) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_redisx_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options_FailOverOptions.ProtoReflect.Descriptor instead.
func (*Options_FailOverOptions) Descriptor() ([]byte, []int) {
	return file_pkg_redisx_config_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Options_FailOverOptions) GetMasterName() *wrapperspb.StringValue {
	if x != nil {
		return x.MasterName
	}
	return nil
}

type Options_MaintNotificationsConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Placeholder for maint notifications config
	Enabled       *wrapperspb.BoolValue   `protobuf:"bytes,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Channel       *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Options_MaintNotificationsConfig) Reset() {
	*x = Options_MaintNotificationsConfig{}
	mi := &file_pkg_redisx_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options_MaintNotificationsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options_MaintNotificationsConfig) ProtoMessage() {}

func (x *Options_MaintNotificationsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_redisx_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options_MaintNotificationsConfig.ProtoReflect.Descriptor instead.
func (*Options_MaintNotificationsConfig) Descriptor() ([]byte, []int) {
	return file_pkg_redisx_config_proto_rawDescGZIP(), []int{1, 2}
}

func (x *Options_MaintNotificationsConfig) GetEnabled() *wrapperspb.BoolValue {
	if x != nil {
		return x.Enabled
	}
	return nil
}

func (x *Options_MaintNotificationsConfig) GetChannel() *wrapperspb.StringValue {
	if x != nil {
		return x.Channel
	}
	return nil
}

var File_pkg_redisx_config_proto protoreflect.FileDescriptor

const file_pkg_redisx_config_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/redisx/config.proto\x12\x06redisx\x1a\x1egoogle/protobuf/duration.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x17pkg/protobufx/tls.proto\"\x8c\x01\n" +
	"\x06Config\x125\n" +
	"\aconfigs\x18\x01 \x03(\v2\x1b.redisx.Config.ConfigsEntryR\aconfigs\x1aK\n" +
	"\fConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.redisx.OptionsR\x05value:\x028\x01\"\xde\x16\n" +
	"\aOptions\x12\x14\n" +
	"\x05addrs\x18\x01 \x03(\tR\x05addrs\x12=\n" +
	"\vclient_name\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"clientName\x12+\n" +
	"\x02db\x18\x03 \x01(\v2\x1b.google.protobuf.Int32ValueR\x02db\x127\n" +
	"\bprotocol\x18\x04 \x01(\v2\x1b.google.protobuf.Int32ValueR\bprotocol\x128\n" +
	"\busername\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\busername\x128\n" +
	"\bpassword\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\bpassword\x12I\n" +
	"\x11sentinel_username\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\x10sentinelUsername\x12I\n" +
	"\x11sentinel_password\x18\b \x01(\v2\x1c.google.protobuf.StringValueR\x10sentinelPassword\x12<\n" +
	"\vmax_retries\x18\t \x01(\v2\x1b.google.protobuf.Int32ValueR\n" +
	"maxRetries\x12E\n" +
	"\x11min_retry_backoff\x18\n" +
	" \x01(\v2\x19.google.protobuf.DurationR\x0fminRetryBackoff\x12E\n" +
	"\x11max_retry_backoff\x18\v \x01(\v2\x19.google.protobuf.DurationR\x0fmaxRetryBackoff\x12<\n" +
	"\fdial_timeout\x18\f \x01(\v2\x19.google.protobuf.DurationR\vdialTimeout\x12<\n" +
	"\fread_timeout\x18\r \x01(\v2\x19.google.protobuf.DurationR\vreadTimeout\x12>\n" +
	"\rwrite_timeout\x18\x0e \x01(\v2\x19.google.protobuf.DurationR\fwriteTimeout\x12R\n" +
	"\x17context_timeout_enabled\x18\x0f \x01(\v2\x1a.google.protobuf.BoolValueR\x15contextTimeoutEnabled\x127\n" +
	"\tpool_fifo\x18\x10 \x01(\v2\x1a.google.protobuf.BoolValueR\bpoolFifo\x128\n" +
	"\tpool_size\x18\x11 \x01(\v2\x1b.google.protobuf.Int32ValueR\bpoolSize\x12<\n" +
	"\fpool_timeout\x18\x12 \x01(\v2\x19.google.protobuf.DurationR\vpoolTimeout\x12A\n" +
	"\x0emin_idle_conns\x18\x13 \x01(\v2\x1b.google.protobuf.Int32ValueR\fminIdleConns\x12A\n" +
	"\x0emax_idle_conns\x18\x14 \x01(\v2\x1b.google.protobuf.Int32ValueR\fmaxIdleConns\x12E\n" +
	"\x10max_active_conns\x18\x15 \x01(\v2\x1b.google.protobuf.Int32ValueR\x0emaxActiveConns\x12F\n" +
	"\x12conn_max_idle_time\x18\x16 \x01(\v2\x19.google.protobuf.DurationR\x0fconnMaxIdleTime\x12E\n" +
	"\x11conn_max_lifetime\x18\x17 \x01(\v2\x19.google.protobuf.DurationR\x0fconnMaxLifetime\x12E\n" +
	"\x10read_buffer_size\x18\x18 \x01(\v2\x1b.google.protobuf.Int32ValueR\x0ereadBufferSize\x12G\n" +
	"\x11write_buffer_size\x18\x19 \x01(\v2\x1b.google.protobuf.Int32ValueR\x0fwriteBufferSize\x124\n" +
	"\n" +
	"tls_config\x18\x1a \x01(\v2\x15.protobufx.TLSOptionsR\ttlsConfig\x12G\n" +
	"\x0fcluster_options\x18\x1b \x01(\v2\x1e.redisx.Options.ClusterOptionsR\x0eclusterOptions\x12J\n" +
	"\x10failover_options\x18\x1c \x01(\v2\x1f.redisx.Options.FailOverOptionsR\x0ffailoverOptions\x12E\n" +
	"\x10disable_identity\x18\x1d \x01(\v2\x1a.google.protobuf.BoolValueR\x0fdisableIdentity\x12E\n" +
	"\x0fidentity_suffix\x18\x1e \x01(\v2\x1c.google.protobuf.StringValueR\x0eidentitySuffix\x12S\n" +
	"\x17failing_timeout_seconds\x18\x1f \x01(\v2\x1b.google.protobuf.Int32ValueR\x15failingTimeoutSeconds\x12A\n" +
	"\x0eunstable_resp3\x18  \x01(\v2\x1a.google.protobuf.BoolValueR\runstableResp3\x12B\n" +
	"\x0fis_cluster_mode\x18! \x01(\v2\x1a.google.protobuf.BoolValueR\risClusterMode\x12f\n" +
	"\x1amaint_notifications_config\x18\" \x01(\v2(.redisx.Options.MaintNotificationsConfigR\x18maintNotificationsConfig\x12A\n" +
	"\x0eenable_tracing\x18# \x01(\v2\x1a.google.protobuf.BoolValueR\renableTracing\x12A\n" +
	"\x0eenable_metrics\x18$ \x01(\v2\x1a.google.protobuf.BoolValueR\renableMetrics\x1a\x94\x02\n" +
	"\x0eClusterOptions\x12@\n" +
	"\rmax_redirects\x18\x01 \x01(\v2\x1b.google.protobuf.Int32ValueR\fmaxRedirects\x127\n" +
	"\tread_only\x18\x02 \x01(\v2\x1a.google.protobuf.BoolValueR\breadOnly\x12D\n" +
	"\x10route_by_latency\x18\x03 \x01(\v2\x1a.google.protobuf.BoolValueR\x0erouteByLatency\x12A\n" +
	"\x0eroute_randomly\x18\x04 \x01(\v2\x1a.google.protobuf.BoolValueR\rrouteRandomly\x1aP\n" +
	"\x0fFailOverOptions\x12=\n" +
	"\vmaster_name\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"masterName\x1a\x88\x01\n" +
	"\x18MaintNotificationsConfig\x124\n" +
	"\aenabled\x18\x01 \x01(\v2\x1a.google.protobuf.BoolValueR\aenabled\x126\n" +
	"\achannel\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\achannelB-Z+github.com/soyacen/grocer/pkg/redisx;redisxb\x06proto3"

var (
	file_pkg_redisx_config_proto_rawDescOnce sync.Once
	file_pkg_redisx_config_proto_rawDescData []byte
)

func file_pkg_redisx_config_proto_rawDescGZIP() []byte {
	file_pkg_redisx_config_proto_rawDescOnce.Do(func() {
		file_pkg_redisx_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_redisx_config_proto_rawDesc), len(file_pkg_redisx_config_proto_rawDesc)))
	})
	return file_pkg_redisx_config_proto_rawDescData
}

var file_pkg_redisx_config_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_redisx_config_proto_goTypes = []any{
	(*Config)(nil),                           // 0: redisx.Config
	(*Options)(nil),                          // 1: redisx.Options
	nil,                                      // 2: redisx.Config.ConfigsEntry
	(*Options_ClusterOptions)(nil),           // 3: redisx.Options.ClusterOptions
	(*Options_FailOverOptions)(nil),          // 4: redisx.Options.FailOverOptions
	(*Options_MaintNotificationsConfig)(nil), // 5: redisx.Options.MaintNotificationsConfig
	(*wrapperspb.StringValue)(nil),           // 6: google.protobuf.StringValue
	(*wrapperspb.Int32Value)(nil),            // 7: google.protobuf.Int32Value
	(*durationpb.Duration)(nil),              // 8: google.protobuf.Duration
	(*wrapperspb.BoolValue)(nil),             // 9: google.protobuf.BoolValue
	(*protobufx.TLSOptions)(nil),             // 10: protobufx.TLSOptions
}
var file_pkg_redisx_config_proto_depIdxs = []int32{
	2,  // 0: redisx.Config.configs:type_name -> redisx.Config.ConfigsEntry
	6,  // 1: redisx.Options.client_name:type_name -> google.protobuf.StringValue
	7,  // 2: redisx.Options.db:type_name -> google.protobuf.Int32Value
	7,  // 3: redisx.Options.protocol:type_name -> google.protobuf.Int32Value
	6,  // 4: redisx.Options.username:type_name -> google.protobuf.StringValue
	6,  // 5: redisx.Options.password:type_name -> google.protobuf.StringValue
	6,  // 6: redisx.Options.sentinel_username:type_name -> google.protobuf.StringValue
	6,  // 7: redisx.Options.sentinel_password:type_name -> google.protobuf.StringValue
	7,  // 8: redisx.Options.max_retries:type_name -> google.protobuf.Int32Value
	8,  // 9: redisx.Options.min_retry_backoff:type_name -> google.protobuf.Duration
	8,  // 10: redisx.Options.max_retry_backoff:type_name -> google.protobuf.Duration
	8,  // 11: redisx.Options.dial_timeout:type_name -> google.protobuf.Duration
	8,  // 12: redisx.Options.read_timeout:type_name -> google.protobuf.Duration
	8,  // 13: redisx.Options.write_timeout:type_name -> google.protobuf.Duration
	9,  // 14: redisx.Options.context_timeout_enabled:type_name -> google.protobuf.BoolValue
	9,  // 15: redisx.Options.pool_fifo:type_name -> google.protobuf.BoolValue
	7,  // 16: redisx.Options.pool_size:type_name -> google.protobuf.Int32Value
	8,  // 17: redisx.Options.pool_timeout:type_name -> google.protobuf.Duration
	7,  // 18: redisx.Options.min_idle_conns:type_name -> google.protobuf.Int32Value
	7,  // 19: redisx.Options.max_idle_conns:type_name -> google.protobuf.Int32Value
	7,  // 20: redisx.Options.max_active_conns:type_name -> google.protobuf.Int32Value
	8,  // 21: redisx.Options.conn_max_idle_time:type_name -> google.protobuf.Duration
	8,  // 22: redisx.Options.conn_max_lifetime:type_name -> google.protobuf.Duration
	7,  // 23: redisx.Options.read_buffer_size:type_name -> google.protobuf.Int32Value
	7,  // 24: redisx.Options.write_buffer_size:type_name -> google.protobuf.Int32Value
	10, // 25: redisx.Options.tls_config:type_name -> protobufx.TLSOptions
	3,  // 26: redisx.Options.cluster_options:type_name -> redisx.Options.ClusterOptions
	4,  // 27: redisx.Options.failover_options:type_name -> redisx.Options.FailOverOptions
	9,  // 28: redisx.Options.disable_identity:type_name -> google.protobuf.BoolValue
	6,  // 29: redisx.Options.identity_suffix:type_name -> google.protobuf.StringValue
	7,  // 30: redisx.Options.failing_timeout_seconds:type_name -> google.protobuf.Int32Value
	9,  // 31: redisx.Options.unstable_resp3:type_name -> google.protobuf.BoolValue
	9,  // 32: redisx.Options.is_cluster_mode:type_name -> google.protobuf.BoolValue
	5,  // 33: redisx.Options.maint_notifications_config:type_name -> redisx.Options.MaintNotificationsConfig
	9,  // 34: redisx.Options.enable_tracing:type_name -> google.protobuf.BoolValue
	9,  // 35: redisx.Options.enable_metrics:type_name -> google.protobuf.BoolValue
	1,  // 36: redisx.Config.ConfigsEntry.value:type_name -> redisx.Options
	7,  // 37: redisx.Options.ClusterOptions.max_redirects:type_name -> google.protobuf.Int32Value
	9,  // 38: redisx.Options.ClusterOptions.read_only:type_name -> google.protobuf.BoolValue
	9,  // 39: redisx.Options.ClusterOptions.route_by_latency:type_name -> google.protobuf.BoolValue
	9,  // 40: redisx.Options.ClusterOptions.route_randomly:type_name -> google.protobuf.BoolValue
	6,  // 41: redisx.Options.FailOverOptions.master_name:type_name -> google.protobuf.StringValue
	9,  // 42: redisx.Options.MaintNotificationsConfig.enabled:type_name -> google.protobuf.BoolValue
	6,  // 43: redisx.Options.MaintNotificationsConfig.channel:type_name -> google.protobuf.StringValue
	44, // [44:44] is the sub-list for method output_type
	44, // [44:44] is the sub-list for method input_type
	44, // [44:44] is the sub-list for extension type_name
	44, // [44:44] is the sub-list for extension extendee
	0,  // [0:44] is the sub-list for field type_name
}

func init() { file_pkg_redisx_config_proto_init() }
func file_pkg_redisx_config_proto_init() {
	if File_pkg_redisx_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_redisx_config_proto_rawDesc), len(file_pkg_redisx_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_redisx_config_proto_goTypes,
		DependencyIndexes: file_pkg_redisx_config_proto_depIdxs,
		MessageInfos:      file_pkg_redisx_config_proto_msgTypes,
	}.Build()
	File_pkg_redisx_config_proto = out.File
	file_pkg_redisx_config_proto_goTypes = nil
	file_pkg_redisx_config_proto_depIdxs = nil
}
