// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pkg/kafkax/config.proto

package kafkax

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       map[string]*Options    `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_pkg_kafkax_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_kafkax_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_pkg_kafkax_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetConfigs() map[string]*Options {
	if x != nil {
		return x.Configs
	}
	return nil
}

type Options struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Receiver      *Options_Receiver       `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Sender        *Options_Sender         `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Brokers       []string                `protobuf:"bytes,3,rep,name=brokers,proto3" json:"brokers,omitempty"`
	Topic         *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=topic,proto3" json:"topic,omitempty"`
	Version       *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Options) Reset() {
	*x = Options{}
	mi := &file_pkg_kafkax_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options) ProtoMessage() {}

func (x *Options) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_kafkax_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options.ProtoReflect.Descriptor instead.
func (*Options) Descriptor() ([]byte, []int) {
	return file_pkg_kafkax_config_proto_rawDescGZIP(), []int{1}
}

func (x *Options) GetReceiver() *Options_Receiver {
	if x != nil {
		return x.Receiver
	}
	return nil
}

func (x *Options) GetSender() *Options_Sender {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *Options) GetBrokers() []string {
	if x != nil {
		return x.Brokers
	}
	return nil
}

func (x *Options) GetTopic() *wrapperspb.StringValue {
	if x != nil {
		return x.Topic
	}
	return nil
}

func (x *Options) GetVersion() *wrapperspb.StringValue {
	if x != nil {
		return x.Version
	}
	return nil
}

type Options_Receiver struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	GroupId       *wrapperspb.StringValue  `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Group         *Options_Receiver_Group  `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Offset        *Options_Receiver_Offset `protobuf:"bytes,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Options_Receiver) Reset() {
	*x = Options_Receiver{}
	mi := &file_pkg_kafkax_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options_Receiver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options_Receiver) ProtoMessage() {}

func (x *Options_Receiver) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_kafkax_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options_Receiver.ProtoReflect.Descriptor instead.
func (*Options_Receiver) Descriptor() ([]byte, []int) {
	return file_pkg_kafkax_config_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Options_Receiver) GetGroupId() *wrapperspb.StringValue {
	if x != nil {
		return x.GroupId
	}
	return nil
}

func (x *Options_Receiver) GetGroup() *Options_Receiver_Group {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *Options_Receiver) GetOffset() *Options_Receiver_Offset {
	if x != nil {
		return x.Offset
	}
	return nil
}

type Options_Sender struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequiredAcks  *wrapperspb.Int32Value `protobuf:"bytes,1,opt,name=required_acks,json=requiredAcks,proto3" json:"required_acks,omitempty"`
	Retry         *Options_Sender_Retry  `protobuf:"bytes,2,opt,name=retry,proto3" json:"retry,omitempty"` // 添加 Retry 消息
	Return        *Options_Sender_Return `protobuf:"bytes,3,opt,name=return,proto3" json:"return,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Options_Sender) Reset() {
	*x = Options_Sender{}
	mi := &file_pkg_kafkax_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options_Sender) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options_Sender) ProtoMessage() {}

func (x *Options_Sender) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_kafkax_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options_Sender.ProtoReflect.Descriptor instead.
func (*Options_Sender) Descriptor() ([]byte, []int) {
	return file_pkg_kafkax_config_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Options_Sender) GetRequiredAcks() *wrapperspb.Int32Value {
	if x != nil {
		return x.RequiredAcks
	}
	return nil
}

func (x *Options_Sender) GetRetry() *Options_Sender_Retry {
	if x != nil {
		return x.Retry
	}
	return nil
}

func (x *Options_Sender) GetReturn() *Options_Sender_Return {
	if x != nil {
		return x.Return
	}
	return nil
}

type Options_Receiver_Group struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Rebalance     *Options_Receiver_Group_Rebalance `protobuf:"bytes,1,opt,name=rebalance,proto3" json:"rebalance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Options_Receiver_Group) Reset() {
	*x = Options_Receiver_Group{}
	mi := &file_pkg_kafkax_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options_Receiver_Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options_Receiver_Group) ProtoMessage() {}

func (x *Options_Receiver_Group) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_kafkax_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options_Receiver_Group.ProtoReflect.Descriptor instead.
func (*Options_Receiver_Group) Descriptor() ([]byte, []int) {
	return file_pkg_kafkax_config_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *Options_Receiver_Group) GetRebalance() *Options_Receiver_Group_Rebalance {
	if x != nil {
		return x.Rebalance
	}
	return nil
}

type Options_Receiver_Offset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Initial       *wrapperspb.Int64Value `protobuf:"bytes,1,opt,name=initial,proto3" json:"initial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Options_Receiver_Offset) Reset() {
	*x = Options_Receiver_Offset{}
	mi := &file_pkg_kafkax_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options_Receiver_Offset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options_Receiver_Offset) ProtoMessage() {}

func (x *Options_Receiver_Offset) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_kafkax_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options_Receiver_Offset.ProtoReflect.Descriptor instead.
func (*Options_Receiver_Offset) Descriptor() ([]byte, []int) {
	return file_pkg_kafkax_config_proto_rawDescGZIP(), []int{1, 0, 1}
}

func (x *Options_Receiver_Offset) GetInitial() *wrapperspb.Int64Value {
	if x != nil {
		return x.Initial
	}
	return nil
}

type Options_Receiver_Group_Rebalance struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	GroupStrategies *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=group_strategies,json=groupStrategies,proto3" json:"group_strategies,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Options_Receiver_Group_Rebalance) Reset() {
	*x = Options_Receiver_Group_Rebalance{}
	mi := &file_pkg_kafkax_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options_Receiver_Group_Rebalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options_Receiver_Group_Rebalance) ProtoMessage() {}

func (x *Options_Receiver_Group_Rebalance) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_kafkax_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options_Receiver_Group_Rebalance.ProtoReflect.Descriptor instead.
func (*Options_Receiver_Group_Rebalance) Descriptor() ([]byte, []int) {
	return file_pkg_kafkax_config_proto_rawDescGZIP(), []int{1, 0, 0, 0}
}

func (x *Options_Receiver_Group_Rebalance) GetGroupStrategies() *wrapperspb.StringValue {
	if x != nil {
		return x.GroupStrategies
	}
	return nil
}

type Options_Sender_RequiredAcks struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *wrapperspb.Int32Value `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Options_Sender_RequiredAcks) Reset() {
	*x = Options_Sender_RequiredAcks{}
	mi := &file_pkg_kafkax_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options_Sender_RequiredAcks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options_Sender_RequiredAcks) ProtoMessage() {}

func (x *Options_Sender_RequiredAcks) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_kafkax_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options_Sender_RequiredAcks.ProtoReflect.Descriptor instead.
func (*Options_Sender_RequiredAcks) Descriptor() ([]byte, []int) {
	return file_pkg_kafkax_config_proto_rawDescGZIP(), []int{1, 1, 0}
}

func (x *Options_Sender_RequiredAcks) GetValue() *wrapperspb.Int32Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type Options_Sender_Retry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Max             *wrapperspb.Int64Value `protobuf:"bytes,1,opt,name=max,proto3" json:"max,omitempty"`                                                  // The total number of times to retry sending a message (default 3).
	Backoff         *durationpb.Duration   `protobuf:"bytes,2,opt,name=backoff,proto3" json:"backoff,omitempty"`                                          // How long to wait for the cluster to settle between retries (default 100ms).
	MaxBufferLength *wrapperspb.Int64Value `protobuf:"bytes,3,opt,name=max_buffer_length,json=maxBufferLength,proto3" json:"max_buffer_length,omitempty"` // The maximum length of the bridging buffer between `input` and `retries` channels in AsyncProducer#retryHandler.
	MaxBufferBytes  *wrapperspb.Int64Value `protobuf:"bytes,4,opt,name=max_buffer_bytes,json=maxBufferBytes,proto3" json:"max_buffer_bytes,omitempty"`    // The maximum total byte size of messages in the bridging buffer between `input` and `retries` channels in AsyncProducer#retryHandler.
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Options_Sender_Retry) Reset() {
	*x = Options_Sender_Retry{}
	mi := &file_pkg_kafkax_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options_Sender_Retry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options_Sender_Retry) ProtoMessage() {}

func (x *Options_Sender_Retry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_kafkax_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options_Sender_Retry.ProtoReflect.Descriptor instead.
func (*Options_Sender_Retry) Descriptor() ([]byte, []int) {
	return file_pkg_kafkax_config_proto_rawDescGZIP(), []int{1, 1, 1}
}

func (x *Options_Sender_Retry) GetMax() *wrapperspb.Int64Value {
	if x != nil {
		return x.Max
	}
	return nil
}

func (x *Options_Sender_Retry) GetBackoff() *durationpb.Duration {
	if x != nil {
		return x.Backoff
	}
	return nil
}

func (x *Options_Sender_Retry) GetMaxBufferLength() *wrapperspb.Int64Value {
	if x != nil {
		return x.MaxBufferLength
	}
	return nil
}

func (x *Options_Sender_Retry) GetMaxBufferBytes() *wrapperspb.Int64Value {
	if x != nil {
		return x.MaxBufferBytes
	}
	return nil
}

type Options_Sender_Return struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Successes     *wrapperspb.BoolValue  `protobuf:"bytes,2,opt,name=successes,proto3" json:"successes,omitempty"`
	Errors        *wrapperspb.BoolValue  `protobuf:"bytes,1,opt,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Options_Sender_Return) Reset() {
	*x = Options_Sender_Return{}
	mi := &file_pkg_kafkax_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options_Sender_Return) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options_Sender_Return) ProtoMessage() {}

func (x *Options_Sender_Return) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_kafkax_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options_Sender_Return.ProtoReflect.Descriptor instead.
func (*Options_Sender_Return) Descriptor() ([]byte, []int) {
	return file_pkg_kafkax_config_proto_rawDescGZIP(), []int{1, 1, 2}
}

func (x *Options_Sender_Return) GetSuccesses() *wrapperspb.BoolValue {
	if x != nil {
		return x.Successes
	}
	return nil
}

func (x *Options_Sender_Return) GetErrors() *wrapperspb.BoolValue {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_pkg_kafkax_config_proto protoreflect.FileDescriptor

const file_pkg_kafkax_config_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/kafkax/config.proto\x12\x06kafkax\x1a\x1egoogle/protobuf/duration.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x8c\x01\n" +
	"\x06Config\x125\n" +
	"\aconfigs\x18\x01 \x03(\v2\x1b.kafkax.Config.ConfigsEntryR\aconfigs\x1aK\n" +
	"\fConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.kafkax.OptionsR\x05value:\x028\x01\"\x84\n" +
	"\n" +
	"\aOptions\x124\n" +
	"\breceiver\x18\x01 \x01(\v2\x18.kafkax.Options.ReceiverR\breceiver\x12.\n" +
	"\x06sender\x18\x02 \x01(\v2\x16.kafkax.Options.SenderR\x06sender\x12\x18\n" +
	"\abrokers\x18\x03 \x03(\tR\abrokers\x122\n" +
	"\x05topic\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\x05topic\x126\n" +
	"\aversion\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\aversion\x1a\x9b\x03\n" +
	"\bReceiver\x127\n" +
	"\bgroup_id\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\agroupId\x124\n" +
	"\x05group\x18\x02 \x01(\v2\x1e.kafkax.Options.Receiver.GroupR\x05group\x127\n" +
	"\x06offset\x18\x03 \x01(\v2\x1f.kafkax.Options.Receiver.OffsetR\x06offset\x1a\xa5\x01\n" +
	"\x05Group\x12F\n" +
	"\trebalance\x18\x01 \x01(\v2(.kafkax.Options.Receiver.Group.RebalanceR\trebalance\x1aT\n" +
	"\tRebalance\x12G\n" +
	"\x10group_strategies\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\x0fgroupStrategies\x1a?\n" +
	"\x06Offset\x125\n" +
	"\ainitial\x18\x01 \x01(\v2\x1b.google.protobuf.Int64ValueR\ainitial\x1a\xee\x04\n" +
	"\x06Sender\x12@\n" +
	"\rrequired_acks\x18\x01 \x01(\v2\x1b.google.protobuf.Int32ValueR\frequiredAcks\x122\n" +
	"\x05retry\x18\x02 \x01(\v2\x1c.kafkax.Options.Sender.RetryR\x05retry\x125\n" +
	"\x06return\x18\x03 \x01(\v2\x1d.kafkax.Options.Sender.ReturnR\x06return\x1aA\n" +
	"\fRequiredAcks\x121\n" +
	"\x05value\x18\x01 \x01(\v2\x1b.google.protobuf.Int32ValueR\x05value\x1a\xfb\x01\n" +
	"\x05Retry\x12-\n" +
	"\x03max\x18\x01 \x01(\v2\x1b.google.protobuf.Int64ValueR\x03max\x123\n" +
	"\abackoff\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\abackoff\x12G\n" +
	"\x11max_buffer_length\x18\x03 \x01(\v2\x1b.google.protobuf.Int64ValueR\x0fmaxBufferLength\x12E\n" +
	"\x10max_buffer_bytes\x18\x04 \x01(\v2\x1b.google.protobuf.Int64ValueR\x0emaxBufferBytes\x1av\n" +
	"\x06Return\x128\n" +
	"\tsuccesses\x18\x02 \x01(\v2\x1a.google.protobuf.BoolValueR\tsuccesses\x122\n" +
	"\x06errors\x18\x01 \x01(\v2\x1a.google.protobuf.BoolValueR\x06errorsB-Z+github.com/soyacen/grocer/pkg/kafkax;kafkaxb\x06proto3"

var (
	file_pkg_kafkax_config_proto_rawDescOnce sync.Once
	file_pkg_kafkax_config_proto_rawDescData []byte
)

func file_pkg_kafkax_config_proto_rawDescGZIP() []byte {
	file_pkg_kafkax_config_proto_rawDescOnce.Do(func() {
		file_pkg_kafkax_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_kafkax_config_proto_rawDesc), len(file_pkg_kafkax_config_proto_rawDesc)))
	})
	return file_pkg_kafkax_config_proto_rawDescData
}

var file_pkg_kafkax_config_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pkg_kafkax_config_proto_goTypes = []any{
	(*Config)(nil),                           // 0: kafkax.Config
	(*Options)(nil),                          // 1: kafkax.Options
	nil,                                      // 2: kafkax.Config.ConfigsEntry
	(*Options_Receiver)(nil),                 // 3: kafkax.Options.Receiver
	(*Options_Sender)(nil),                   // 4: kafkax.Options.Sender
	(*Options_Receiver_Group)(nil),           // 5: kafkax.Options.Receiver.Group
	(*Options_Receiver_Offset)(nil),          // 6: kafkax.Options.Receiver.Offset
	(*Options_Receiver_Group_Rebalance)(nil), // 7: kafkax.Options.Receiver.Group.Rebalance
	(*Options_Sender_RequiredAcks)(nil),      // 8: kafkax.Options.Sender.RequiredAcks
	(*Options_Sender_Retry)(nil),             // 9: kafkax.Options.Sender.Retry
	(*Options_Sender_Return)(nil),            // 10: kafkax.Options.Sender.Return
	(*wrapperspb.StringValue)(nil),           // 11: google.protobuf.StringValue
	(*wrapperspb.Int32Value)(nil),            // 12: google.protobuf.Int32Value
	(*wrapperspb.Int64Value)(nil),            // 13: google.protobuf.Int64Value
	(*durationpb.Duration)(nil),              // 14: google.protobuf.Duration
	(*wrapperspb.BoolValue)(nil),             // 15: google.protobuf.BoolValue
}
var file_pkg_kafkax_config_proto_depIdxs = []int32{
	2,  // 0: kafkax.Config.configs:type_name -> kafkax.Config.ConfigsEntry
	3,  // 1: kafkax.Options.receiver:type_name -> kafkax.Options.Receiver
	4,  // 2: kafkax.Options.sender:type_name -> kafkax.Options.Sender
	11, // 3: kafkax.Options.topic:type_name -> google.protobuf.StringValue
	11, // 4: kafkax.Options.version:type_name -> google.protobuf.StringValue
	1,  // 5: kafkax.Config.ConfigsEntry.value:type_name -> kafkax.Options
	11, // 6: kafkax.Options.Receiver.group_id:type_name -> google.protobuf.StringValue
	5,  // 7: kafkax.Options.Receiver.group:type_name -> kafkax.Options.Receiver.Group
	6,  // 8: kafkax.Options.Receiver.offset:type_name -> kafkax.Options.Receiver.Offset
	12, // 9: kafkax.Options.Sender.required_acks:type_name -> google.protobuf.Int32Value
	9,  // 10: kafkax.Options.Sender.retry:type_name -> kafkax.Options.Sender.Retry
	10, // 11: kafkax.Options.Sender.return:type_name -> kafkax.Options.Sender.Return
	7,  // 12: kafkax.Options.Receiver.Group.rebalance:type_name -> kafkax.Options.Receiver.Group.Rebalance
	13, // 13: kafkax.Options.Receiver.Offset.initial:type_name -> google.protobuf.Int64Value
	11, // 14: kafkax.Options.Receiver.Group.Rebalance.group_strategies:type_name -> google.protobuf.StringValue
	12, // 15: kafkax.Options.Sender.RequiredAcks.value:type_name -> google.protobuf.Int32Value
	13, // 16: kafkax.Options.Sender.Retry.max:type_name -> google.protobuf.Int64Value
	14, // 17: kafkax.Options.Sender.Retry.backoff:type_name -> google.protobuf.Duration
	13, // 18: kafkax.Options.Sender.Retry.max_buffer_length:type_name -> google.protobuf.Int64Value
	13, // 19: kafkax.Options.Sender.Retry.max_buffer_bytes:type_name -> google.protobuf.Int64Value
	15, // 20: kafkax.Options.Sender.Return.successes:type_name -> google.protobuf.BoolValue
	15, // 21: kafkax.Options.Sender.Return.errors:type_name -> google.protobuf.BoolValue
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_pkg_kafkax_config_proto_init() }
func file_pkg_kafkax_config_proto_init() {
	if File_pkg_kafkax_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_kafkax_config_proto_rawDesc), len(file_pkg_kafkax_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_kafkax_config_proto_goTypes,
		DependencyIndexes: file_pkg_kafkax_config_proto_depIdxs,
		MessageInfos:      file_pkg_kafkax_config_proto_msgTypes,
	}.Build()
	File_pkg_kafkax_config_proto = out.File
	file_pkg_kafkax_config_proto_goTypes = nil
	file_pkg_kafkax_config_proto_depIdxs = nil
}
